### ISSUE TITLE
[v5] shared element stuck when navigating away to another screen

### ISSUE THREAD

**Issue by panvourtsis** [IjzerenHein/react-navigation-shared-element#100]
### problem and how i got it
Using the library i created a list of item that when clicked navigates to a new screen where the image is shared. So far all good, going from page A to B with the shared item works perfectly. 

Now when i move away from screen B to screen C where there is no shared item between them the shared item from B stuck for a while and the disappears.

i tried several changes on routes but the only thing that is working is to have them in different stacks which is not what we want.

### route config
Screen A = Home
Screen B = Food
Screen C = Order
```
function HomeStack() {
  return (
    <Stack.Navigator initialRouteName="Home" headerMode={'none'}>
      <Stack.Screen name="Home" component={HomeScreen} />
      <Stack.Screen
        name="Food"
        component={FoodScreen}
        options={{
          cardStyleInterpolator: ({ current: { progress } }) => {
            return { cardStyle: { opacity: progress } };
          },
        }}
      />
      <Stack.Screen name="Order" component={OrderScreen} />
    </Stack.Navigator>
  );
}
```
### Video
See video's last transition to see the problem
![ezgif com-resize](https://user-images.githubusercontent.com/6433679/93003200-6688a080-f545-11ea-96af-900d153b9030.gif)

### Packages
```
"@react-navigation/native": "5.1.5",
"@react-navigation/stack": "5.2.10",
"react-native-shared-element": "^0.7.0",
"react-navigation": "^4.4.0",
"react-navigation-shared-element": "next",
"react-navigation-stack": "^2.8.2"
```

**Comment by panvourtsis** [comment]
**Solution:** Playing around a bit i found that if i declare in the screen that i move from (Screen B) the below it understands to stop having it ready when showing is `false`

```
Food.sharedElements = (navigation, otherNavigation, showing) => {
  const product = navigation?.params?.product ?? {};
  if (showing) {
    return [product.id];
  }
};
```

**Comment by thecoorum** [comment]
@panvourtsis did you have an issue when coming back from the final screen, shared element is not visible initially and only after transition finish?
