### ISSUE TITLE
An argument for 'routeConfigs' was not provided.

### ISSUE THREAD

**Issue by D10S60948** [IjzerenHein/react-navigation-shared-element#105]
Hi, 

First of all - Thank you for your effort and amazing contribution!!

My issue:
Using react-navigation v5 (routes as components style) and when typing this:
_const Stack = createSharedElementStackNavigator();_

I'm getting this error:
**_Expected 2-3 arguments, but got 0.ts(2554)
createSharedElementStackNavigator.d.ts(3, 52): An argument for 'routeConfigs' was not provided._**

Is v5 is not supported yet?? Am I doing something wrong?

Thanks again

**Comment by anastely** [comment]
Are you solve it?

**Comment by D10S60948** [comment]
Yes.I did.
Issue can be marked as solved.

Documentation for react-navigation-5 can be improved.

Thank you for the great work!


‫בתאריך יום א׳, 1 בנוב׳ 2020 ב-20:14 מאת ‪Anas T‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by JCBsystem** [comment]
@D10S60948 please share 
what did you do to fix it ?

**Comment by D10S60948** [comment]
I fixed it by following the documentation in:
_**https://github.com/IjzerenHein/react-navigation-shared-element/tree/navigation-v5**_
instead of:
_**https://github.com/IjzerenHein/react-native-shared-element**_

or in other words:
npm i react-navigation-shared-element@next

**Comment by IjzerenHein** [comment]
Hi! I believe these problems are fixed by the latest release, which officially supports React Navigation 5 and 6. Please upgrade. https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment]
Closing this issue. Feel free to reopen with additional info or repro case in the `example` app.
