### ISSUE TITLE
Image disappears on android while transition

### ISSUE THREAD

**Issue by youssef212** [IjzerenHein/react-navigation-shared-element#113]
i am using shared transition in a lot of situations right now , when i use the shared transition under complicated screen or navigation it always feels buggy and laggy, the lag happens and the outcome is some weird transitions sometimes the transition is delayed sometimes the image disappears , sometimes the animation changes to fade on its own as well , after looking at all the issues here nothing really helped me (like changing the transition config to timing instead of spring).

[here is a sample video](https://streamable.com/weub0g)
hint: i am using shared element in other part with spring even and it works perfect but itsn't consistent

**Comment by IjzerenHein** [comment]
Ah, I think I know what's happening here. There was a problem on Android which caused parts of the shared-element to be clipped. From your video, I can see that the content is wrongly clipped during the transition. This may also explain the blinking sometimes. This should be fixes as of v0.8.0 of `react-native-shared-element`.
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.0

**Comment by IjzerenHein** [comment]
Closing this as this should be fixed. Feel free to reopen with additional info and a repro case in the `example` app if this is still a problem with the latest official version.
