### ISSUE TITLE
[v5] ANDROID transition not triggered when using the default goBack button in stack navigator

### ISSUE THREAD

**Issue by danielzzz** [IjzerenHein/react-navigation-shared-element#114]
hi, 

it seems that the shared element work well forwards and backwards when using the back button, but it's not triggered when using the stock header back button.

thanks, cheers, dan

**Comment by razvanbretoiu** [comment]
@danielzzz did you solve it? I'm facing the same issue on Android

**Comment by danielzzz** [comment]
not sure, I think I just left it as it was, waiting for any news here

**Comment by MatheusPires99** [comment]
I am facing this problem on iOS.

**Comment by jzxchiang1** [comment]
Any update on this? Facing the same issue.

**Comment by hikhtiartaJNE** [comment]
Set gestureEnabled to false, its solved for me

**Comment by IjzerenHein** [comment]
Hi! I believe this was a problem with the early 3.0.0 prerelease version. Please upgrade to the latest version, which supports React Navigation 5 and 6 officially.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment]
The `example` app contains many test-cases and I am unable to reproduce this problem with the latest version. I'm going to close this issue thereof. Feel free to reopen with a test-case in the `example` app in case this is still a problem.
