### ISSUE TITLE
module for V3 Unable to resolve "react-navigation-stack" from "node_modules\react-navigation-shared-element\build\v4\createSharedElementStackNavigator.js"

### ISSUE THREAD

**Issue by dodicandra** [IjzerenHein/react-navigation-shared-element#115]
### this module seems to collide with react-navigation-stack, or in its incomplete documentation so it doesn't find this module in my project expo

![image](https://user-images.githubusercontent.com/48325708/98419718-3b8b7a80-20b8-11eb-814c-2a29e4557e06.png)

![image](https://user-images.githubusercontent.com/48325708/98419768-54942b80-20b8-11eb-8192-d040d5bcff23.png)

# if i am wrong please tell me how to install it properly

**Comment by Kyi-Moe-Min** [comment]
@dodicandra have you found the solution? I facing the same issue
