### ISSUE TITLE
Couldn't register the sharedElementStackNavigator with new version of React-Navigation

### ISSUE THREAD

**Issue by JamesDMar** [IjzerenHein/react-navigation-shared-element#119]
I get the following error 

![Simulator Screen Shot - iPhone 11 - 2020-11-23 at 12 43 26](https://user-images.githubusercontent.com/26965271/100014168-de1b4d00-2d8a-11eb-8e9c-4ee529d8a4c5.png)

**Comment by IjzerenHein** [comment]
Too little info, closing
