### ISSUE TITLE
[v5] Error with goBack on stack of same screen.

### ISSUE THREAD

**Issue by Trashpants** [IjzerenHein/react-navigation-shared-element#126]
So im struggling to describe this but I have this setup:

```
    <Stack.Navigator initialRouteName="Dashboard">
      <Stack.Screen name="Dashboard" component={DashboardScreen} />
      <Stack.Screen
        name="Detail"
        component={DetailScreen}
        sharedElements={(route, otherRoute, showing) => {
          const { details } = route.params;
          return [
            {
              id: `MainImage.${image.id}`,
              debug: true
            }
          ];
        }}
      />
    </Stack.Navigator>
```

Within each of my `DetailScreen` I have an action to push another `DetailScreen` to the Stack. 
The action works and it will animate correctly as I push to the stack.

However the moment I attempt to `navigate.goBack()` it seems to break entirely, and holds the specific `MainImage.${image.id}` in memory somewhere as it stops that animation from working again (when pushing to the stack) until the app is restarted.

Any ideas how to get around this?

I've tried `return []` within shared elements when the `route.key` matches `otherRoute.key` but makes no difference

**Comment by Waheed-Rumaneh** [comment]
@Trashpants 
i was have the same problem and i research so much to solve it 
i tried so many solutions but nothing worked 

finally i solve it and this is the solution that worked for me if you want try it 
just add this in   DetailScreen option :

 **options={{  ...TransitionPresets.FadeFromBottomAndroid, }}** 

this will prevent the shared element default animation that make this bug when close the page from Top to Bottom

**Comment by Trashpants** [comment]
unfortunately this hasn't made a different to my issue :(

**Comment by Waheed-Rumaneh** [comment]
My solution work with the original back button from device and you can back also when swipe down on details screen but it's NOT work on custom back button

**Comment by Trashpants** [comment]
Hmm ive tried it on both an android and iOS device, I already had a custom config for my screen interpolation:

```
<Stack.Screen
  name="Detail"
  component={DetailScreen}
  options={{
            header: () => null,
            headerTransparent: true,
            cardStyleInterpolator: ({
              current,
            }: StackCardInterpolationProps) => {
              return {
                overlayStyle: {
                  opacity: current.progress.interpolate({
                    inputRange: [0, 1],
                    outputRange: [0, 0.2]
                  })
                },
                cardStyle: {
                  opacity: current.progress.interpolate({
                    inputRange: [0, 1],
                    outputRange: [0, 1]
                  })
                }
              };
            }
          }}
  sharedElements={(route, otherRoute, showing) => {
    const { details } = route.params;
    return [
      {
        id: `MainImage.${image.id}`,
        debug: true
      }
    ];
  }}
/>
```

but removing everything and going back to the android transition you suggested hasn't; fixed the issue - The animation works fine pushing to the stack but popping from the stack is where the error seems to occur :(

**Comment by Waheed-Rumaneh** [comment]
try this:
import { createStackNavigator, TransitionPresets } from '@react-navigation/stack';
<Stack.Navigator mode="modal">
<Stack.Screen
  name="Detail"
  component={DetailScreen}
  options={{

    tabBarVisible: false, headerShown: false,
    animationEnabled: true,
    gestureEnabled: Platform.OS === 'android',
    transitionSpec: {
        open: {
            animation: 'timing',
            config: {
                duration: 500,
            },
        },
        close: {
            animation: 'timing',
            config: {
                duration: 500,
            },
        },
    },
    gestureDirection: 'vertical',
    gestureVelocityImpact: 0.5,
    cardStyle: { backgroundColor: 'transparent' },
    cardOverlayEnabled: true,
    gestureResponseDistance: {
        vertical: 100,
    },
    ...TransitionPresets.FadeFromBottomAndroid,
}} 
  sharedElements={(route, otherRoute, showing) => {
    const { details } = route.params;
    return [
      {
        id: `MainImage.${image.id}`,
        debug: true,
        animation: 'fade',
      }
    ];
  }}
/>
</Stack.Navigator>

**Comment by Trashpants** [comment]
unfortunately it hasn't worked either - I think its something to do with shared transitions config dealing with pushing the same screen to the stack multiple times. As I said it works perfectly when pushing to the stack but popping is where the error seems to be :(

**Comment by antstu** [comment]
is this the same issue you are having?
https://www.reddit.com/r/reactnative/comments/kmeoy0/issue_with_react_navigation_shared_element/
I've also been trying to figure it out to no avail...

**Comment by Trashpants** [comment]
Nope mines a case of because I keep adding the same detail screen, the shared element just doesn’t animate at all.


I think In your case you need to basically disable the standard stack animation, so update your cardStyleInterpolator screen o be the same as mine - remove x translation animation

**Comment by antstu** [comment]
i tried updating the cardStylerInterpolator to yours - it didn't fix the issue. Sometimes the animation works correctly but mostly it doesn't

**Comment by KawaljeetCuelogic** [comment]
Please have a look at my issue here: https://github.com/IjzerenHein/react-navigation-shared-element/issues/147#issuecomment-788140353 @Trashpants . I suspect you are facing something similar to this. Please let me know if you've (by any chance) overcome this. 

Any help would be much appreciated.

**Comment by Trashpants** [comment]
> Please have a look at my issue here: [#147 (comment)](https://github.com/IjzerenHein/react-navigation-shared-element/issues/147#issuecomment-788140353) @Trashpants . I suspect you are facing something similar to this. Please let me know if you've (by any chance) overcome this.
> 
> Any help would be much appreciated.

Pretty much just gave up with using the library to be completely honest, these transitions are fantastic when they work, but the library seems barely maintained at this point :(

**Comment by KawaljeetCuelogic** [comment]
> > Please have a look at my issue here: [#147 (comment)](https://github.com/IjzerenHein/react-navigation-shared-element/issues/147#issuecomment-788140353) @Trashpants . I suspect you are facing something similar to this. Please let me know if you've (by any chance) overcome this.
> > Any help would be much appreciated.
> 
> Pretty much just gave up with using the library to be completely honest, these transitions are fantastic when they work, but the library seems barely maintained at this point :(

Ah. So by any chance did you try any other library or workaround for shared elements?

**Comment by Waheed-Rumaneh** [comment]
I used it again and it's working fine when i used it between two pages including Bottom Bar
Project video :
https://drive.google.com/file/d/1Yn2lBVEFwwh7DUm6tUIxhahfDX4RIQnG/view?usp=drivesdk

**Comment by KawaljeetCuelogic** [comment]
@Waheed-Rumaneh Can you please share the overview of your code or how have you achieved it?

**Comment by EmreKorpe** [comment]
Unfortunately I disabled the android shared function on closing the page. My workaround

```
CategoryDetails.sharedElements = (route,_,showing) => {
  const { item } = route.params;
  if(Platform.OS === 'ios'){
  return [
    {
      id: `item.${item.id}.image_url`,
      animation: 'move',
      resize: 'clip'
    },
    {
      id: `item.${item.id}.title`,
      animation: 'fade',
      resize: 'clip'
    },
    {
      id: `item.${item.id}.description`,
      animation: 'fade',
      resize: 'clip'
    },
    {
      id: `item.${item.id}.iconName`,
      animation: 'move',
      resize: 'clip'
    }
  ];
}else{
  if(showing){
    return [
      {
        id: `item.${item.id}.image_url`,
        animation: 'move',
        resize: 'clip'
      },
      {
        id: `item.${item.id}.title`,
        animation: 'fade',
        resize: 'clip'
      },
      {
        id: `item.${item.id}.description`,
        animation: 'fade',
        resize: 'clip'
      },
      {
        id: `item.${item.id}.iconName`,
        animation: 'move',
        resize: 'clip'
      }
    ];
  }else{
    return []
  }
}
};
```

**Comment by IjzerenHein** [comment]
Hi! Thanks for reporting this. I've added a test-case to the `example` app for testing Push/Pop behaviour of the same-screen. See video.

https://user-images.githubusercontent.com/6184593/130594453-2250411e-5c90-47d4-a094-e9e19cb88322.mp4

For React Navigation 5/6 this seems to be working as expected (also on Android). It's possible that the problem has already been fixed in the latest official release (which contained a bunch of bug fixes). Please upgrade to the latest version and/or update the test-case in the `example` app to reflect the problem you are having.

https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment]
Closing this issue as this appears to be working correctly with the latest official release and react-navigation 5/6
