### ISSUE TITLE
Hide element in last screen programmatically

### ISSUE THREAD

**Issue by Hirbod** [IjzerenHein/react-navigation-shared-element#13]
Hi @IjzerenHein,

I've spent a lot of time with this bindings and your package (using expo).
I wanted to achieve a similar shared transition on iOS as WhatsApp does.

I am using a special Stack with a transparent background. My view has a white background which I wan't to interpolate while dragging the element using PanGesture from RNGH. Everything is working finally as I want it (only the borderRadius animation is broken, already posted an issue).

Anyway, since I am interpolating the background, I can see, that the shared element in the routerStack is already visible again, and as soon as I release my finger, it gets hidden. 

This is great when using the default back gesture, but not when I interpolate (since this will trigger the animation). 

Is there a way to programmatically trigger "hide the element on the last screen"?
To make it more clear, I've recorded a video.

https://youtu.be/h782F9Q-7D0

I am demonstrating multiple cases, which all work fine but the last not. (U see, the image is there when I release the finger and disappears and appears again). This wasn't a issue without the navigator card being transparent, but it has to be this way.

```js
const userStack = createSharedElementStackNavigator(
    createStackNavigator, {
        User: {screen: User},
        UserImage: {screen: UserImage},
    },
    {
        ...StackNavigatorOptions,
        transparentCard: true,
        cardStyle: {
            backgroundColor: "transparent"
        },
        transitionConfig: () => springyFadeIn(),
    },
);
```

**Comment by Hirbod** [comment]
So I think that all the magic happens here:
https://github.com/IjzerenHein/react-navigation-shared-element/blob/b01ddb1db7161a49dbfb66d657c5dc1b56daff49/src/createSharedElementScene.tsx#L75

You hide the element behind the current view when willFocus navigation event is triggered. I only need to find an option to trigger willFocus manually (and revert it if the user cancels). Is there any way I could do that currently?

**Comment by IjzerenHein** [comment]
Perhaps taking a look at Williams video will help:
https://www.youtube.com/watch?v=83GNiMp-qq0
