### ISSUE TITLE
All shared elements goes on top left corner when going back to previous screen.

### ISSUE THREAD

**Issue by pietroanello** [IjzerenHein/react-navigation-shared-element#130]
I was trying to replicate a project seen on YouTube using React Navigation v5 and Shared Elements, but for some reason, even if the code is the same, this strange issue always happen. 

Video 1 - List is the first screen and Detail the second. When i go **from List to Detail** everything is good, but when I go back all the shared elements moves to the top left corner of the screen, before disappearing and reappearing in position.

![video-1](https://user-images.githubusercontent.com/43348480/102014564-e5fd5a00-3d56-11eb-8f93-df13b6f85866.gif)

Video 2 - _This is the most strange case._ Detail is the first screen and List the second. Everything works for the first cycle (**from Detail to List and from List to Detail**), then the problem appear again.

![video-2](https://user-images.githubusercontent.com/43348480/102014575-f6add000-3d56-11eb-8e2c-43e31f46f449.gif)

Maybe the problem is related to the package versions, but I don't know, I tried everything.

```
"dependencies": {
    "@ant-design/icons-react-native": "^2.2.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.16.1",
    "react-native-shared-element": "^0.7.0",
    "react-navigation-shared-element": "^5.0.0-alpha1",
    "typescript": "^2.9.2"
  }
```

**Comment by heron2014** [comment]
I had similar issue, I have noticed I had applied:

```import { enableScreens } from 'react-native-screens';```
```enableScreens();``` in my root navigator. Removing enableScreens() fixed the issue.

**Comment by pietroanello** [comment]
> I had similar issue, I have noticed I had applied:
> 
> `import { enableScreens } from 'react-native-screens';`
> `enableScreens();` in my root navigator. Removing enableScreens() fixed the issue.

You literally saved my life. Thanks!

**Comment by KyleAsaff** [comment]
omg, i spent a whole day trying to debug this. removing `enableScreens();` worked for me too 🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️ thanks for this!

**Comment by imamrobani** [comment]
it happens only on iOS when you use enableScreeens().
because on Android running well

**Comment by nhuesmann** [comment]
`react-native-screens` offers a huge performance increase, so disabling it isn't really a solution. Has anyone found out how to resolve this issue while still using `react-native-screens`?

**Comment by Planetfunky** [comment]
Few months later removing `enableScreens()` doesnt fix the issue on ios

**Comment by pietroanello** [comment]
Have you tried restarting the metro bundler or the app? My advice Is to start with something really simple and check if it works, in that way you can be sure its not a code faultIl 13 mag 2021 18:15, Kev Artik ***@***.***> ha scritto:
Few months later removing enableScreens() doesnt fix the issue on ios

**Comment by Planetfunky** [comment]
Yeah. In fact I've tried to replicate the same project as yours an also this `https://blog.logrocket.com/how-to-use-shared-element-transition-with-react-navigation-v5/` on the lastest expo sdk 41 and also on a bare react native project. Both project on both enviroments with the same result on ios. But perhaps you're right it maybe some something else causing this if I'm the only one still experiencing this issue 😭

**Comment by jcdoughty** [comment]
I’m seeing this exact same issue. Did you find a solution?

**Comment by duducv** [comment]
I had this problem and  solve using this config on Navigator:
thanks to https://gist.github.com/mrousavy/6029c7a4eb58f7603e79a136053ff976

export const iosTransitionSpec = {
  animation: "spring",
  config: {
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 10,
    restSpeedThreshold: 10,
  },
};
    <SharedElementStack.Navigator
      mode="modal"
      screenOptions={{
        useNativeDriver: true,
        // Enable gestures if you want. I disabled them because of my card style interpolator opacity animation
        gestureEnabled: false,
        // gestureResponseDistance: {
        // 	vertical: 100,
        // },
        // gestureDirection: 'vertical',
        ...TransitionPresets.ModalSlideFromBottomIOS,
        transitionSpec: {
          open: iosTransitionSpec,
          close: iosTransitionSpec,
        },
        // Opacity animation, you can also adjust this by playing with transform properties.
        cardStyleInterpolator: ({ current: { progress } }) => ({
          cardStyle: {
            opacity: progress,
          },
        }),
      }}
      headerMode="none"
    >
......
/>

**Comment by Root-ish** [comment]
In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

**Comment by jzxchiang1** [comment]
> In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

This worked for me too.

**Comment by aryanm5** [comment]
> In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

This worked for me. If you want to keep the left-to-right swipe gesture to go back (instead of the top-to-bottom that comes with `"modal"`), add `gestureDirection: horizontal` to your screen options.

**Comment by Shik1997** [comment]
> In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

this worked for me too.thanks.

**Comment by imamrobani** [comment]
thanks a lot

**Comment by hani-q** [comment]
> In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

You saved my life

**Comment by Zi-ji** [comment]
> In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.

Hi, I'm also facing this issue and I'm using react-navigation v6.
In react-navigation v6, mode prop is deprecated:
https://reactnavigation.org/docs/upgrading-from-5.x/#modemodal-is-removed-in-favor-of-presentation-modal
And the whole modal screen behavior is changed in v6, so this solution doesn't work for me. Also for me, shared elements will go to the top left no matter how I move between screens. My project relies on some latest v6 features so I cannot fall back, unfortunately. Any idea how to solve this issue?

**Comment by IjzerenHein** [comment]
I believe that setting `mode="modal"` deactivates `detachInactiveScreens` of react-native-screens, which might explain why that fixes the problem. The latest official release disables `detachInactiveScreens` by default as no solution for this has been found yet,

**Comment by IjzerenHein** [comment]
> Hi, I'm also facing this issue and I'm using react-navigation v6.
> In react-navigation v6, mode prop is deprecated:
> https://reactnavigation.org/docs/upgrading-from-5.x/#modemodal-is-removed-in-favor-of-presentation-modal
> And the whole modal screen behavior is changed in v6, so this solution doesn't work for me. Also for me, shared elements will go to the top left no matter how I move between screens. My project relies on some latest v6 features so I cannot fall back, unfortunately. Any idea how to solve this issue?

Are you using the latest official version? Please add a repro to the `example` app so this can be investigated further.

**Comment by likeSo** [comment]
> > In case anybody might still be looking. For me adding `mode="modal"` to the `SharedElementStack.Navigator` worked.
> 
> Hi, I'm also facing this issue and I'm using react-navigation v6.
> In react-navigation v6, mode prop is deprecated:
> https://reactnavigation.org/docs/upgrading-from-5.x/#modemodal-is-removed-in-favor-of-presentation-modal
> And the whole modal screen behavior is changed in v6, so this solution doesn't work for me. Also for me, shared elements will go to the top left no matter how I move between screens. My project relies on some latest v6 features so I cannot fall back, unfortunately. Any idea how to solve this issue?

I am also using react-navigation v6, and my shared elements go top right corner when going back, i will try the latest version of shared elements

**Comment by duytran1999** [comment]
I have same problem after delete enableScreens();
![ezgif-4-3d73c85c3829](https://user-images.githubusercontent.com/52518518/132162059-9348801b-74e1-4383-aefb-793ccf68c206.gif)
 Line 11
![image](https://user-images.githubusercontent.com/52518518/132161889-4dfb8dfa-49ee-4bb5-b5ad-61c8556ed7fc.png)

**Comment by jsindos** [comment]
> I believe that setting `mode="modal"` deactivates `detachInactiveScreens` of react-native-screens, which might explain why that fixes the problem. The latest official release disables `detachInactiveScreens` by default as no solution for this has been found yet.
> https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

This issue was also occurring for me on the iOS simulator using `@react-navigation/native@6.0.4` and `react-navigation-shared-element@3.1.3`, passing in `detachInactiveScreens={false}` prop to `SharedElementStack.Navigator` fixed it for me, thanks for the hint.

**Comment by devzaveri** [comment]
Hey @pietroanello,
I want to know that how you done that animation. 
I want to move my element from bottom left corner to to right corner I am using React-native-reanimated library. but I am not able to do that animation can you please gide me
