### ISSUE TITLE
[v5] Elements doesn't transition if I move them in separate components

### ISSUE THREAD

**Issue by pietroanello** [IjzerenHein/react-navigation-shared-element#132]
I'm just facing this strange behavior. If I create two screen components inside the App.js and mount the shared navigator, everything works, but if I move the single components in separate files, the transition stop working.

What can I do? Am i missing something? Obv I export and import them properly in the App.js

**Comment by pietroanello** [comment]
I really don't know what happened but now everything works...

**Comment by ydv0121** [comment]
Hello @pietroanello 
same issue happened with me i have created header component separate and want to add shared transition in it but it's not working can you help me with this?

`<HeaderMenu/>` is component.

index.js
```
 const item = props.route.params.item
    return (
        <View style={{ flex: 1 }}>
            <HeaderMenu item={item} navigation={props.navigation} />
            <FlatList
                ref={flatRef}
                contentContainerStyle={{ flexGrow: 1, justifyContent: 'flex-end' }}
                data={chatData}
                renderItem={({ item, index }) => <MessageList item={item} index={index} />}
                keyExtractor={(item, index) => index.toString()}
                onContentSizeChange={() => flatRef.current.scrollToEnd({ animated: true })}
            />
            <SafeAreaView style={{ backgroundColor: 'lightblue' }}>
                <Input msgValue={msg} textMessage={textMessage} onPress={() => _sendMessage()} />
            </SafeAreaView>
        </View>
    )
```
HeaderMenu.js
```
       <View>
            <TouchableOpacity onPress={() => navigation.goBack()}>
                  <Icon type={"MaterialIcons"} name={Platform.OS == 'ios' ? "arrow-back-ios" : 'arrow-back'} />
             </TouchableOpacity>   
          <View>
               <SharedElement id={`item.${item.id}.photo`}>
                         <Image source={require("../../avatar2.png")} style={{ height: 30, width: 30 }} />
               </SharedElement>
          </View>
       </View>
HeaderMenu.sharedElements = (navigation, otherNavigation, showing) => {
    const item = navigation.params.item
    return [`item.${item.id}.photo`];
};
```

**Comment by pietroanello** [comment]
Hi Yash,

I don't see where is the other component with the transition element.
For shared elemtns to work you've to set a <SharedElement> in both screens.

So for example, you can pass the width or the height in the <HeaderMenu> component, and then use it with different options in two different screens.
Then the transition should work.

Let me know.
Pietro

P.s. I don't know why but I can't see your answer on GitHub inside the issue. Maybe open a new one so I can answer better there.

________________________________
Da: Yash Vaghela <notifications@github.com>
Inviato: martedì 5 gennaio 2021 07:28
A: IjzerenHein/react-navigation-shared-element <react-navigation-shared-element@noreply.github.com>
Cc: pietroanello <pietro.anello@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [IjzerenHein/react-navigation-shared-element] [v5] Elements doesn't transition if I move them in separate components (#132)


Hello @pietroanello<https://github.com/pietroanello>
same issue happened with me i have created header component separate and want to add shared transition in it but it's not working can you help me with this?

<HeaderMenu/> is component.

index.js

 const item = props.route.params.item
    return (
        <View style={{ flex: 1 }}>
            <HeaderMenu item={item} navigation={props.navigation} />
            <FlatList
                ref={flatRef}
                contentContainerStyle={{ flexGrow: 1, justifyContent: 'flex-end' }}
                data={chatData}
                renderItem={({ item, index }) => <MessageList item={item} index={index} />}
                keyExtractor={(item, index) => index.toString()}
                onContentSizeChange={() => flatRef.current.scrollToEnd({ animated: true })}
            />
            <SafeAreaView style={{ backgroundColor: 'lightblue' }}>
                <Input msgValue={msg} textMessage={textMessage} onPress={() => _sendMessage()} />
            </SafeAreaView>
        </View>
    )


HeaderMenu.js

       <View>
            <TouchableOpacity onPress={() => navigation.goBack()}>
                  <Icon type={"MaterialIcons"} name={Platform.OS == 'ios' ? "arrow-back-ios" : 'arrow-back'} />
             </TouchableOpacity>
          <View>
               <SharedElement id={`item.${item.id}.photo`}>
                         <Image source={require("../../avatar2.png")} style={{ height: 30, width: 30 }} />
               </SharedElement>
          </View>
       </View>
HeaderMenu.sharedElements = (navigation, otherNavigation, showing) => {
    const item = navigation.params.item
    return [`item.${item.id}.photo`];
};
