### ISSUE TITLE
Files gets deleted after installing @react-navigation/native@^5.0.9 

### ISSUE THREAD

**Issue by Saad9624** [IjzerenHein/react-navigation-shared-element#138]
After installing specfic versions of @react-navigation/native@^5.0.9 and @react-navigation/stack@^5.1.1  causing  deletion of some files from original react navigation and unable to run in

**Comment by IjzerenHein** [comment]
This library has only peer-dependencies on react-navigation and does not affect your react-navigation installing. For installing react-navigation (4/5/6), please follow the instructions at https://reactnavigation.org/docs/getting-started#installation
