### ISSUE TITLE
Weird Bounce and Shift on Android Only

### ISSUE THREAD

**Issue by macist-m** [IjzerenHein/react-navigation-shared-element#139]
Hello, there is this weird effect happening only on android... Any help would be great...

Thanks...

![ezgif-4-901741c20191](https://user-images.githubusercontent.com/58189781/105578585-64a3d900-5d92-11eb-839a-d1b6b0128e79.gif)

"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/native": "^5.9.2",
"@react-navigation/stack": "^5.14.1",
"install": "^0.13.0",
"npm": "^6.14.11",
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-gesture-handler": "^1.9.0",
"react-native-reanimated": "^1.13.2",
"react-native-safe-area-context": "^3.1.9",
"react-native-screens": "^2.15.2",
"react-native-shared-element": "^0.7.0",
"react-navigation-fluid-transitions": "^0.3.2",
"react-navigation-shared-element": "^5.0.0-alpha1"

**Comment by macist-m** [comment]
Fading in the image fixed this using cardStyleInterpolator on the single view stack...

Here -> https://github.com/IjzerenHein/react-navigation-shared-element/issues/35#issuecomment-627242545

**Comment by skinnynpale** [comment]
it helps for me

```
 <Stack.Screen
          ...
          options={{ ...TransitionPresets.SlideFromRightIOS }}
          ... >
```

**Comment by NeerajDana** [comment]
having the same issue any solution the one mentioned did not worked

**Comment by IjzerenHein** [comment]
Hi! `react-native-shared-element@0.7.0` did not process scale transitions on Android correctly. Please upgrade to https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.0 or higher. This fixes the new Android transition preset `ScalefromCenterAndroid` which is the default react-navigation preset on newer Android phones.

**Comment by IjzerenHein** [comment]
Closing this issue. Feel free to reopen with additional details and a repro case in the `example` app if this is still a problem

**Comment by Grey-1011** [comment]
# I'm facing the same issue. Has anyone solved it yet?
       
      
   
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-reanimated": "^3.8.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-shared-element": "^0.8.9",
    "react-navigation-shared-element": "^3.1.3"
