### ISSUE TITLE
Possible to edit the positions of the end nodes?

### ISSUE THREAD

**Issue by muhammedjailam** [IjzerenHein/react-navigation-shared-element#142]
The end nodes positions are a bit off. And the resizing stretch doesn't clearly scale to the size. (Probably because the endnode doesnt align properly? 

Is it possible to adjust the position of the end nodes (relative to the positions they will be) using style attribute so any other method to adjust the positions of the end nodes?

**Comment by KawaljeetCuelogic** [comment]
Hey please have a look at my problem here: https://github.com/IjzerenHein/react-navigation-shared-element/issues/147#issuecomment-788140353

Please let me know if you're also facing similar problem?

**Comment by IjzerenHein** [comment]
I think this was because of issues in the native code (should be fixes in v0.8.0). Please upgrade to the latest `react-native-shared-element` code:
https://github.com/IjzerenHein/react-native-shared-element/releases
