### ISSUE TITLE
[v5] [expo40] BackTransitionPosition is X & Y = 0

### ISSUE THREAD

**Issue by sanborN93** [IjzerenHein/react-navigation-shared-element#143]
After updating to SDK 40, I noticed that the position of the SharedElement no longer fits correctly. To be exact, the position is always X = 0 and Y = 0 or in other words top left.

The transition to the new screen works perfectly. Only navigating back has the wrong position of the SharedElement.

In Expo SDK39 everything works fine.

Does anyone have an idea if adjustments are necessary or is it really a bug?

Here is a video of the working SDK39 and the Bug in SDK40

https://user-images.githubusercontent.com/17229407/107542275-50504080-6bc8-11eb-9a76-27443c0e05a2.mov

https://user-images.githubusercontent.com/17229407/107542299-5514f480-6bc8-11eb-8237-11c468dc10ac.mov

SDK39 Diagnostics:
Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.22.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^4.4.3 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

SDK40 Diagnostics:
 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.22.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.3 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Comment by jcdoughty** [comment]
I’m seeing this exact same issue. Did you find a solution?

**Comment by sanborN93** [comment]
Yes I have solved it. I closed the thread because I did not read the instructions correctly. In the changes of expo 40 it said that react native screens does not work with it.

So I stopped using react native screens and everything ran as usual.
