### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by tydesantya** [IjzerenHein/react-navigation-shared-element#145]
Hi, thank you for creating this library
I was amazed on how this library creates a new level for RN apps, however i can't seem to find a compatible dependencies for this library, as for each versions of react-navigation-stack i use with different versions of this library seems to cause different errors (some versions caused the element to stuck, if it's not stuck then it's not transitioning on .goBack(), if it's working on .goBack() then the transition is flickering
Is there a preset of the dependencies i can follow in order for this library to work perfectly ?

**Comment by tydesantya** [comment]
I tried running the example for v4 and v5 and it's working properly there too

**Comment by traingethermarc** [comment]
Have you figured out anything? What was your solution :)? Thanks!

**Comment by IjzerenHein** [comment]
Hi! This library has (unfortunately) been in a prerelease state for a long time. The prerelease had some problems with dependencies and I understand it was not very clear on how to use it.
A new major version has just been released with official support for React Navigation 5 and 6. It also supports React Navigation 4 through a separate import path. Please have a look at the latest README and the documentation for use with React Navigation 4 and 5/6:

https://github.com/IjzerenHein/react-navigation-shared-element#documentation
