### ISSUE TITLE
any plans to upgrade to match react-navigation v6?

### ISSUE THREAD

**Issue by chj-damon** [IjzerenHein/react-navigation-shared-element#159]
react-navigation v6 is coming soon, it will be great if there's a plan to upgrade this amazing library to match it?

I really love both reanimated2 and this library!

**Comment by traingethermarc** [comment]
not even working with v5 :(

**Comment by IjzerenHein** [comment]
A new major version has just been released which supports both react-navigation 5 and 6. Please upgrade and let me know if you run into any problems.

https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2
