### ISSUE TITLE
Error 'onTransitionStart' is moved to 'navigationOptions'. Specify it in 'defaultNavigationOptions' to keep the same behaviour.

### ISSUE THREAD

**Issue by sa8ab** [IjzerenHein/react-navigation-shared-element#17]
just tried to create a project and do shared element effect, after setting up I got this error:

'onTransitionStart' is moved to 'navigationOptions'. Specify it in 'defaultNavigationOptions' to keep the same behaviour.

also same for onTransitionEnd

**Comment by IjzerenHein** [comment]
Hi, unfortunately this library does not yet support `react-navigation-stack` v2. In v2 the whole animation/gesture control was overhauled and the screen transition progress is exposed completely differently. Please use react-navigation-stack@v1 for now still

**Comment by sa8ab** [comment]
Yes fixed, thank you for answer. closing the issue.
Do you have plan about making it work with stack@v2?

btw you can close the issue

**Comment by IjzerenHein** [comment]
Yes I absolutely want it to work with the latest react-navigation-stack and react-navigation (v5)!
