### ISSUE TITLE
Problem with shared element not doing the intended transition with a component in a flatlist.

### ISSUE THREAD

**Issue by ismaelbarry** [IjzerenHein/react-navigation-shared-element#174]
Below is my code after following the correct set up guides. 

What's different is that I have a Flatlist rendering a component (which I import) and I pass the sharedElementID to that component. However, the intended animation still doesn't work. Below is a screenshot of my code.

![Screen Shot 2021-07-20 at 12 28 30 AM (2)](https://user-images.githubusercontent.com/13290756/126262124-0ee7929a-74f9-4cb9-bf71-bb90f8790b14.png)

Could someone please point me in the right direction as to solving this issue? Thanks! :)

**Comment by nandorojo** [comment]
It seems like your IDs have no unique identifiers. Make sure that you give a unique ID from each list item so that the screens know what to transition. It should be something like `image-${id}`
