### ISSUE TITLE
Question about how tab bar is hidden while navigating in the Example project (BottomTabs2.tsx)

### ISSUE THREAD

**Issue by ismaelbarry** [IjzerenHein/react-navigation-shared-element#188]
Hi @IjzerenHein !! Thanks for the wonderful library and the example project. 😊

I'm interested to know how you were able to hide the tab bar under the example "BottomTabs2" for react navigation v4 and v5. I've been playing around with the demo and searching through the files, but I found no clues as to how the tab bar transitioned to hidden when navigating to the detailed screen.

I'd much appreciate your help. Thanks in advance and keep up the excellent work!

**Comment by IjzerenHein** [comment]
Hi! Please have a look at this from the BottomTabs2 example and think about it closely.

```tsx
export default () => (
  <NavigationContainer>
    <Stack.Navigator>
      <Stack.Screen name={name} component={TabScreen} />
      <Stack.Screen name="Detail" component={DetailScreen} />
    </Stack.Navigator>
  </NavigationContainer>
);
```

When you navigate to the `DetailScreen`, the whole TabNavigator is pushed is pushed back and only `DetailScreen` is visible, which is inside a Stack navigator.

**Comment by IjzerenHein** [comment]
Closing this as the answer has been provided. Feel free to reopen with additional details if the solution didn't work
