### ISSUE TITLE
defaultNavigationOptions not working

### ISSUE THREAD

**Issue by sa8ab** [IjzerenHein/react-navigation-shared-element#19]
Hi,
Added defaultNavigaionOptions on App.js for createSharedElementStackNavigator but does not work.
trying to add options like gestureEnabled, transitoinSpec, cardStyleInterpolator, but no one is working

"react-navigation-stack": "^2.1.1",
"react-navigation-shared-element": "^2.0.1",
"react-native-shared-element": "~0.5.1",

**Comment by tankers746** [comment]
I've create PR to fix this @IjzerenHein 
https://github.com/IjzerenHein/react-navigation-shared-element/pull/20

**Comment by IjzerenHein** [comment]
Thanks @tankers746 🙏

**Comment by IjzerenHein** [comment]
I've merged the PR and published a new version:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.0.2
