### ISSUE TITLE
react-navigation v5 support

### ISSUE THREAD

**Issue by kennetpostigo** [IjzerenHein/react-navigation-shared-element#2]
With the rewrite of react-navigation to a component-first api, how does support for it end up working out and will it be supported?

**Comment by IjzerenHein** [comment]
I thought the component first-API was just an exploration at this stage?

As for supporting it, that should be fairly straightforward. I could imagine perhaps the following API. It's also possible that shared-elements because an integral part of react-navigation, in that case you wouldn't even need to specify `<SharedElement.Navigator>`

```jsx
function App() {
  return (
    <NavigationContainer>
      <SharedElement.Navigator component={Stack.Navigator} initialRouteName="main">
        <Stack.Screen name="main" component={Main} />
        <Stack.Screen
          name="detail"
          component={Detail}
          sharedElements={() => ['photo']}
          />
      </SharedElement.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by satya164** [comment]
We released the 5.0 alpha few weeks back and it will be the next major release of React Navigation.

It would be awesome to have a shared element navigator for v5. We have some docs on building custom navigators here: https://reactnavigation.org/docs/en/next/custom-navigators.html

We don't have docs for typescript yet, but you can check the existing navigators to get an idea: https://github.com/react-navigation/navigation-ex/blob/master/packages/stack/src/navigators/createStackNavigator.tsx

cc @brentvatne

**Comment by IjzerenHein** [comment]
Yes, definitely, the new API looks amazing! I will take a closer look once I return from vacation.

**Comment by FRizzonelli** [comment]
@IjzerenHein Any news? I'd like to keep using your awesome shared element with v5!

**Comment by IjzerenHein** [comment]
Hi! No sorry no news on this yet. I've been too busy with some deadlines. Could really use some help on this one. Who wants to help out?

**Comment by andreibarabas** [comment]
@IjzerenHein if you agree, I can help out by putting a small $100 bounty on this issue, to get it solved faster. 

I'm thinking we could use issuehunt or bountysource to pay the bounty to whoever provides quality code for the v5 support.

Let me know you thoughts.

**Comment by IjzerenHein** [comment]
Yeah that would be great, any help in this area would be appreciated!

As for current progress, I've been working on getting stack@2 up & running. This mostly works, with exception of some glitches here and there, which are mostly due to navigation/stack lifecycles events not emitted in all scenarios.

As for react-navigation@5. A good start would be to have some example code on how to capture scene lifecycle events and how to capture the underlying animated-value.

**Comment by satya164** [comment]
For events, you can use `navigation.addListener` for each screen:

- `focus` - screen comes into focus, equivalent to `willFocus`
- `blur` - screen goes out of focus, equivalent to `willBlur`, in case of gestures, it'll fire after the screen is closed
- `transitionStart` - screen's transition animation starts, for gestures, fires after you lift the finger
- `transitionEnd`- screen's transition animation ends

To get the animated values, `useCardAnimation().current.progress`) `@react-navigation/stack`, same as stack v2.

**Comment by andreibarabas** [comment]
> Yeah that would be great, any help in this area would be appreciated!
> 
> As for current progress, I've been working on getting stack@2 up & running. This mostly works, with exception of some glitches here and there, which are mostly due to navigation/stack lifecycles events not emitted in all scenarios.
> 
> As for react-navigation@5. A good start would be to have some example code on how to capture scene lifecycle events and how to capture the underlying animated-value.

I can post the bounty on it, just need you to add the repo to such a site, like issuehunt or bountysource. I can't do it because it needs to be the owner / contributor of the repo. If you can post the link here once it's done, I'll do the rest

**Comment by IjzerenHein** [comment]
Awesome, thanks for the information @satya164 🤝

@andreibarabas Sounds good! Which one would you prefer, issuehunt or bountysource (I have no experience with either of them) ?

**Comment by andreibarabas** [comment]
@IjzerenHein neither have I :) but issuehunt seems to have a cleaner UI :) so let's try that one

**Comment by IjzerenHein** [comment]
I've went with bountysource. Here is the link:
https://www.bountysource.com/issues/79875203-react-navigation-v5-support

**Comment by sunnylqm** [comment]
@IjzerenHein You can also sign up in [brave](https://publishers.basicattentiontoken.org/) so users of brave browser can give you tips directly

![image](https://user-images.githubusercontent.com/615282/73341589-ed8b5000-42b7-11ea-8170-be2041925667.png)

**Comment by IjzerenHein** [comment]
> @IjzerenHein You can also sign up in brave so users of brave browser can give you tips directly

Thanks for the suggestion @sunnylqm

**Comment by andreibarabas** [comment]
@IjzerenHein - done. 

For anyone that completes this quality, feel free to press "SOLVE ISSUE" on this page

https://www.bountysource.com/issues/79875203-react-navigation-v5-support

**Comment by mattmogford** [comment]
Is there a start to v5 branch yet to start from?
Willing to give this a go. We are already using v5 so have a few months experience with it.

**Comment by andreibarabas** [comment]
hey @mattmogford - glad to hear that. I don't think there is. @IjzerenHein ?

**Comment by IjzerenHein** [comment]
That's right, no branch has been started yet, master has the latest code.

**Comment by darrylyoung** [comment]
First off, this package looks great. Nice work! Typically, after just finishing 2 days of upgrading my app to React Navigation 5, I just came across this and saw that it doesn’t yet support version 5. It looks like it’s worth waiting for, though. Thanks for all your hard work.

**Comment by Tiltorito** [comment]
Hi @IjzerenHein, do you have an estimation of how long it might take to add support for v5?

**Comment by IjzerenHein** [comment]
It's a couple days work at most

**Comment by andreibarabas** [comment]
@mattmogford - did you start work on it by any chance? would anyone else like to contribute either with increasing the bounty or providing the solution and claiming it?

**Comment by cbrevik** [comment]
I took a shot at this yesterday, and I've got a basic hacky example working with v5 @ https://github.com/AtB-AS/react-navigation-shared-element/commit/eaadb5d1422c2c3807fafac4010f0ac7109f36b2

Right now I return `Navigator`, `Screen` and `wrapComponent` from `createSharedElementStackNavigator`. The `wrapComponent` is just a convenience function right now, and going to remove it eventually.

Unsure if my approach is correct, but I'm going to hack on this some more to see if it leads anywhere.

**Comment by 592da** [comment]
whats the status ?

**Comment by IjzerenHein** [comment]
The status is that I've worked on some other issues over the weekend and merged this PR into a new `navigation-v5` branch. Haven't gotten around to test anything yet though..

**Comment by IjzerenHein** [comment]
Hello everyone. I've released an initial of the react-navigation@5 support to NPM using the `@next` tag.
This can be considered in alpha stage, so please report any bugs as new issues in this repo.
[Please checkout the README on the v5 branch on how to get started with the v5 support](https://github.com/IjzerenHein/react-navigation-shared-element/tree/navigation-v5)

Many thanks to @cbrevik for making this possible. ❤️

**Comment by andreibarabas** [comment]
@IjzerenHein - will check it out !

**Comment by FRizzonelli** [comment]
@IjzerenHein Hype is real! Gonna try it out asap :) Thanks man!

**Comment by cbrevik** [comment]
Fantastic, thanks @IjzerenHein! 😊

**Comment by nataly-chobat** [comment]
Thank you so much for supporting react-navigation v5!

I faced a problem with building app on android. Here is the error
```
Execution failed for task ':react-native-shared-element:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
It might be stupid issue but anyway I need someone's help. Thank you in advance!

**Comment by IjzerenHein** [comment]
For anyone using React Navigation 5. A new version has been prereleased which supports both the react-navigation 4.x and 5.x APIs from a single codebase.
Please use that for testing from now on:
https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/README-prerelease.md

**Comment by VytautasLozickas** [comment]
Metro build fails with the latest pre-release version when only the v5 versions of react navigation and stack are installed:
```
error: Error: Unable to resolve module `react-navigation-stack` from `node_modules/react-navigation-shared-element/build/v4/createSharedElementStackNavigator.js`: react-navigation-stack could not be found within the project.
```

**Comment by IjzerenHein** [comment]
Ah of course. Will fix shortly, thanks for letting me know 👍

**Comment by VytautasLozickas** [comment]
Also this file: https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/src/createSharedElementStackNavigator.tsx has a lot of stuff in it and that makes it hard or close to impossible (without copying the entire thing) to make a custom Navigator that uses a custom Router. It would be nice to extract the View used within the Navigator and a factory creation function that wraps both Navigator and Screen components. That would make it possible to create a custom `createSharedElementStackNavigator` function that uses a custom Router inside without copying a lot of the shared-element-related code.

**Comment by AnasAlamin** [comment]
> Ah of course. Will fix shortly, thanks for letting me know 👍

is this fixed ? i still have this issue.

**Comment by pke** [comment]
Its not solved yet, you need to install the v4 libs as dependencies for now.
I've added those to my `devDependencies`

```
"react-navigation": "^4.3.7",
"react-navigation-stack": "^2.3.11"
```

See #79

**Comment by qmzik** [comment]
> Ah of course. Will fix shortly, thanks for letting me know 👍

Hey, man! What's the status of this issue? You promised to fix it shortly 😢 

Also you didn't connect brave wallet, I want to send you some BAT tokens, to motivate you 🚀 

> @IjzerenHein You can also sign up in [brave](https://publishers.basicattentiontoken.org/) so users of brave browser can give you tips directly
> 
> ![image](https://user-images.githubusercontent.com/615282/73341589-ed8b5000-42b7-11ea-8170-be2041925667.png)

**Comment by thisisgit** [comment]
> For events, you can use `navigation.addListener` for each screen:
> 
> * `focus` - screen comes into focus, equivalent to `willFocus`
> * `blur` - screen goes out of focus, equivalent to `willBlur`, in case of gestures, it'll fire after the screen is closed
> * `transitionStart` - screen's transition animation starts, for gestures, fires after you lift the finger
> * `transitionEnd`- screen's transition animation ends
> 
> To get the animated values, `useCardAnimation().current.progress` from `@react-navigation/stack`, same as stack v2.

For those who are here to find out a way to detect when screen transition ends, and tried out above solutions (`transitionEnd` & `useCardAnimation`) but didn't work, [this solution](https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes) worked out for me:
```
useFocusEffect(
  React.useCallback(() => {
    const task = InteractionManager.runAfterInteractions(() => {
      // Triggers when screen transition ends
    });

    return () => task.cancel();
  }, [])
);
```

**Comment by IjzerenHein** [comment]
Landed officially for React Navigation 5 & 6 🚀 🎉
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2
