### ISSUE TITLE
Error: React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by WrathChaos** [IjzerenHein/react-navigation-shared-element#204]
<img width="849" alt="CleanShot 2021-10-03 at 22 49 51@2x" src="https://user-images.githubusercontent.com/6813862/135769275-de47da2f-ee40-4497-92dd-daf346acdc8e.png">

```jsx
import * as React from "react";
import { Platform } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { isReadyRef, navigationRef } from "react-navigation-helpers";
import { createSharedElementStackNavigator } from "react-navigation-shared-element";
/**
 * ? Local Imports
 */
import { SCREENS } from "@shared-constants";
// ? Screens
import HomeScreen from "@screens/home/HomeScreen";
import SplashScreen from "@screens/splash/SplashScreen";
import SignUpScreen from "@screens/sign-up/SignUpScreen";

const Stack = createSharedElementStackNavigator();


const Navigation = () => {
  React.useEffect((): any => {
    return () => (isReadyRef.current = false);
  }, []);

  return (
    <NavigationContainer
      ref={navigationRef}
      onReady={() => {
        isReadyRef.current = true;
      }}
    >
      <Stack.Navigator
        mode="modal"
        screenOptions={{
          headerShown: false,
          cardStyleInterpolator: ({ current: { progress } }) => ({
            cardStyle: {
              opacity: progress,
            },
          }),
        }}
      >
        <Stack.Screen name={SCREENS.SPLASH} component={SplashScreen} />
        <Stack.Screen
          name={SCREENS.HOME}  component={HomeScreen}  />
        <Stack.Screen name={SCREENS.SIGN_UP} component={SignUpScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default Navigation;

```

I cannot use `react-navigation-shared-element` on **ANDROID**. It works great on iOS. On android it throws this error. When I deleted the two Stack.Screen it works with 1 screen but there is no logic for that. 

Can you help me?

**Comment by WrathChaos** [comment]
Complete my bad, I did not wrap the `SharedElement` component's child.

**Comment by LuuNguyen0811** [comment]
@WrathChaos I have same issue, how to fix this?, what's the component's child you use?

**Comment by LuuNguyen0811** [comment]
`<TouchableOpacity
      style={styles.item}
      activeOpacity={1}
      onPress={() => onClick(item)}>
      <SharedElement id={`${item.id}.1`}>
        <SharedElement id={`${item.id}`}>
          <FastImage source={images.hoguom} style={styles.itemImage} />

          <LinearGradient
            colors={['rgba(0, 0, 0, 0)', 'rgba(66, 112, 106, 100)']}
            style={styles.blurItem}
          />
        </SharedElement>

        <View style={styles.contentItem}>
          <Text style={styles.labelPlace}>{item.city}</Text>
          <Text numberOfLines={8} style={styles.desc}>
            {item.desc}
          </Text>
          <View style={styles.discoverContainer}>
            <Text style={styles.discoverText}>Discover Place</Text>
            <Image source={images.ic_arrow_right} style={styles.icDiscover} />
          </View>
        </View>
      </SharedElement>
    </TouchableOpacity>`
    my item
