### ISSUE TITLE
Stange animation

### ISSUE THREAD

**Issue by guiguil81** [IjzerenHein/react-navigation-shared-element#22]
Hello,

First of all thanks you for this asome package ;)

I try to implement a basic transition animation between a card and a view.
I have record my animation and the little bug here: [https://streamable.com/s/i77es/dxknbq](url)

ps: Sorry it's my first post on github and i don't find how add indentation on my code, if you can explain me, i will edit my code.

My code:

Navigation: 
```
const ExplorerRoute = createSharedElementStackNavigator(
  {
    Explorer: {screen: Explorer},
    OneSeance: {screen: OneSeance},
  },
  {
    headerMode: 'none',
    initialRouteName: 'Explorer',
  },
);
```

myCardListView
```
{seances.map((item, index) => (
  <Fragment key={item.id + 'cardSeance'}>
    <CardSeance
      item={item}
      onPress={value => this.navigateToOneSeance(value)}
    />
    {index + 1 !== seances.length && <Separator value={8} />}
  </Fragment>
))}
```

oneCardSeance
```
<SharedElement id={props.item.id + 'cardSeance'}>
  <View>
    <Image
      style={styles.imageCardSeance}
      source={{uri: props.item.picture}}
    />
    <View style={styles.containerBlackFilterCardSeance} />
    <Text style={styles.titleCardSeance}>{props.item.title}</Text>
  </View>
</SharedElement>
```

And my view after click on one card:
```
<SharedElement
  id={oneSeance.id + 'cardSeance'}
  style={styles.imageTitleOneSeance}>
  <View style={styles.imageTitleOneSeance}>
    <Image
      style={styles.imageTitleOneSeance}
      source={{uri: oneSeance.picture}}
    />
    <View style={styles.containerTitleOneSeance}>
      <Text style={styles.textTitleOneSeance}>{oneSeance.title}</Text>
      <View style={styles.containerDurationOneSeance}>
        <Text style={styles.textDurationOneSeance}>
          {oneSeance.duration}min
        </Text>
      </View>
    </View>
    <View style={styles.blackFilterOneSeance} />
  </View>
</SharedElement>
OneSeance.sharedElements = (navigation, otherNavigation, showing) => {
  const item = navigation.getParam('data');
  return [item.id + 'cardSeance'];
};
```

I don't know if this "bug" is normal or not.

**Comment by IjzerenHein** [comment]
Hi. You can put back-ticks around your code, also called fenced code blocks:
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by IjzerenHein** [comment]
> First of all thanks you for this asome package ;)

Thanks :)

Hi, the problem here is that there is a <View> inside <SharedElement>. And since the other View has different dimensions, this will cause the whole View to be stretched to the size of the new view.

What you should do to get a perfect transition, is to put each element in its own <SharedElement> container.

Like so:

```
<SharedElement is='image'>
  <Image ... />
</SharedElement>

<SharedElement is='title'>
  <Text ...>
</SharedElement>
```
