### ISSUE TITLE
Glitch when navigate from details screen to any another screen [IOS + Android]

### ISSUE THREAD

**Issue by ahmadzraiq** [IjzerenHein/react-navigation-shared-element#238]
Hello, 
The library works perfectly on Android and IOS, but I have an issue when I navigate from details screen to any another screen the image get stuck for a moment

Check the following video :-

https://user-images.githubusercontent.com/43582061/168596275-6485b35d-4d1c-4de0-91ac-64cb8f8c697f.mp4

Environments:-
`
"react-native": "0.64.0"
"@react-navigation/native": "^6.0.10",
"@react-navigation/stack": "^6.2.1",
"react-navigation-shared-element": "^3.1.3"
"react-native-gesture-handler": "~1.10.3"
`

**Comment by philipthedeveloper** [comment]
> Hello, The library works perfectly on Android and IOS, but I have an issue when I navigate from details screen to any another screen the image get stuck for a moment
> 
> Check the following video :-
> 
>  iPhone.12.mp4 
> Environments:- `"react-native": "0.64.0" "@react-navigation/native": "^6.0.10", "@react-navigation/stack": "^6.2.1", "react-navigation-shared-element": "^3.1.3" "react-native-gesture-handler": "~1.10.3"`

I am facing the same problem right now, is there any possible fix?😥😥

**Comment by ahmadzraiq** [comment]
Waiting

**Comment by miahabdu** [comment]
@philipthedeveloper @ahmadzraiq I had the same issue and found the solution here: https://github.com/IjzerenHein/react-navigation-shared-element/issues/100
