### ISSUE TITLE
Animation is normal react-navigation animation

### ISSUE THREAD

**Issue by jmsims2** [IjzerenHein/react-navigation-shared-element#25]
I'm working on a simple example and thus far when navigating between screens, I just get the normal animation you'd get with react-navigation.  Not sure what I'm doing wrong here?

Here is my truncated App.js:

```
const AppNavigator = createSharedElementStackNavigator({
  LoginScreen,
  OauthScreen,
  ActivitiesScreen,
  ActivityDetail
});

const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}
```

Then I have a list view, that I converted into just a single item centered on the page...this is the ListItem element:
```
return (
      <TouchableWithoutFeedback onPress={this.goToDetail}>
        <SharedElement id={`card-${this.props.item.activityid}`}>
          <View
            style={{
              backgroundColor: "white",
              flexDirection: "row",
              borderStyle: "solid",
              borderWidth: "1px",
              borderRadius: "4px",
              margin: 5,
              shadowOffset: { width: 2, height: 4 },
              shadowOpacity: 0.5,
              shadowRadius: 1,
              elevation: 5,
              height: 100,
              padding: 10
            }}
          >
            <View
              style={{
                borderRadius: "50%",
                backgroundColor: "black",
                height: 30,
                width: 30,
                justifyContent: "center",
                alignItems: "center",
                shadowOffset: { width: 1, height: 2 },
                shadowOpacity: 0.3,
                shadowRadius: 2,
                elevation: 2
              }}
            >
              <MaterialIcons size={20} name="phone" color="white" />
            </View>
            <View
              style={{
                justifyContent: "flex-start",
                alignItems: "center",
                marginTop: 5,
                marginLeft: 10
              }}
            >
              <Text
                style={{
                  fontSize: 16,
                  color: "black"
                }}
              >
                {this.props.item.subject}
              </Text>
            </View>
          </View>
        </SharedElement>
      </TouchableWithoutFeedback>
    );
  }
```
Then I have a detail view that also has the element above at the top:
```
const ActivityDetail = props => {
  const item = props.navigation.getParam("item");
  return (
    <SafeAreaView style={styles.container}>
      <SharedElement id={`card=${item.activityid}`}>
        <ListItem style={styles.card} item={item} />
      </SharedElement>
    </SafeAreaView>
  );
};

ActivityDetail.sharedElements = (navigation, otherNavigation, showing) => {
  const item = navigation.getParam("item");
  console.log("PARAM ITEM", item.activityid);
  return [{ id: `card-${item.activityid}`, animation: "move" }];
};
```
Here is a gif of the animation.  Just following the examples, I would have expected the list item to move to the top, rather than the screen to swipe in from the right....again, not sure what I'm doing wrong here?

![activity animation](https://user-images.githubusercontent.com/2560527/75005523-fb05a700-542b-11ea-8c57-77686d7fa78e.gif)

**Comment by IjzerenHein** [comment]
I think your id in `ActivityDetail` is wrong (it contains '=', and not '-'):

```
<SharedElement id={`card-${this.props.item.activityid}`}>
```

```
<SharedElement id={`card=${item.activityid}`}>
```

**Comment by jmsims2** [comment]
Oh jeez...good catch.  Updated that though and get the same result...below is the gif.

I'm logging out the actual activityid and it's the same.  Not sure what else I have wrong.  I swear I have stared at your example for hours and also watched a video from William Candillon that uses it....nothing glaringly stands out.

![activity animation 2](https://user-images.githubusercontent.com/2560527/75046376-303ce400-5482-11ea-93cb-8c1a6039e355.gif)

**Comment by IjzerenHein** [comment]
I'd put a console.log in all your views, just to make sure all Id's are the same.

Also, is your `ActivityDetail.sharedElements` function being called, and are you returned the correct ids there?

Which version of react-navigation-stack are using?

**Comment by jmsims2** [comment]
Yep, all the ids are the same.

Here is the sharedElements function....I don't notice anything in there that is off...it is being called.

```
ActivityDetail.sharedElements = (navigation, otherNavigation, showing) => {
  const item = navigation.getParam("item");
  console.log("PARAM ITEM", item.activityid);
  return [`card-${item.activityid}`];
};
```

The version of react-navigation-stack is `"react-navigation-stack": "^2.1.1"`  I'm using expo sdk36 if that makes a difference?

**Comment by IjzerenHein** [comment]
Well there have been some important updates to the `react-native-shared-element` lib, that will be released in SDK 37, but still, I believe this example should have worked.
 
I really don't know, what if you set the id to a hardcoded value?

**Comment by davidrenji** [comment]
I was having the same issue, the transition was the normal navigation animation.
But then I changed the return statement, instead of returning just the id in the array, I returned an array with an object like this:

`return [{id: 'myUniqueId'}];`

And after that it worked.

**Comment by jmsims2** [comment]
Thanks for the suggestions....tried them both.  Hardcoded the id and that didn't work and then turned it into an object instead and same thing, still the normal nav animation.

I may just start a new project from scratch and see if I can get it to work, maybe I have a messed up dependency somewhere....not really sure what else to try.

I do appreciate all the help...looking forward to getting it working, all the examples look great!

**Comment by davidrenji** [comment]
ok, I forgot to mention that I'm using a class component and use this at the top of the class:

`static sharedElements = (navigation, otherNavigation, showing) => {
    const item = navigation.getParam('item');    
    return [{ id: item.id}];
};`

**Comment by jmsims2** [comment]
Thanks David.  I converted to class components and same deal...normal navigation still.  William Candillon posted a boilerplate for his airbnb shared transition video, so I may try starting from that (assuming it has all the right dependencies) and try and get it to work from there.  I'll let you guys know if I get it fixed.  Appreciate all the help!

**Comment by jmsims2** [comment]
So I went back and started from William Candillon's boilerplate.  I first got his airbnb stuff working from his example.  Next, I moved all of my screens and components into that project and attempted to get the transition working and it still did not work.  Do there need to be any specific styles on the child of the SharedElement component?  I notice most examples are for an Image...I have a custom component that is just a view that is formatted like a card, will Views work?  Since I got the airbnb one to work, I'm thinking there must be a problem with what I am trying to transition?

**Comment by IjzerenHein** [comment]
Hmm, this is weird indeed. So it worked with Williams boilerplate and then you made some changes and it stopped working, correct? In that case you'd probably take the problem on step by step. Converting Williams code to yours and check which step makes it break.

**Comment by bcgilliom** [comment]
I hit the same thing, and what it turned out to be for me was importing `SharedElement` from `react-native-shared-element` instead of `react-navigation-shared-element` - that's an easy one to miss for quite a while - no errors or anything!

**Comment by jmsims2** [comment]
Thanks @bcgilliom. We since got this working, redid the whole thing from the boiler plate mentioned above.  After going back through some old branches, I noticed we were doing the same exact thing!  Now importing the right thing and all is working...completely missed that while investigating the issue.
