### ISSUE TITLE
Hello, both state and getParam are deprecated. Any work arounds?

### ISSUE THREAD

**Issue by darias08** [IjzerenHein/react-navigation-shared-element#256]
Hello, I am seeing that the .state and .getParam are both deprecated when using this block of code. Is there any work arounds when using this code? I am trying not to have any broken transitions when I am transitioning to a third screen with a sharedElement. 

```jsx
ModelScreen.sharedElements = (navigation, otherNavigation, showing) => {
  if (otherNavigation.state.routeName === 'LogoList') {
    const name = navigation.getParam('name');
    return [{
        id: name,
        // animation: 'fade',
    }];
  }
};

```

![deprecated](https://user-images.githubusercontent.com/58616895/205514515-e98e2e5f-5ce7-4d7d-8e52-63aae70e9794.PNG)

_Originally posted by @IjzerenHein in https://github.com/IjzerenHein/react-navigation-shared-element/issues/27#issuecomment-591851276_

**Comment by NosikuZedSport** [comment]
what was the solution?
