### ISSUE TITLE
Need to stop the shared animation for other screen.

### ISSUE THREAD

**Issue by sa8ab** [IjzerenHein/react-navigation-shared-element#27]
Hi. Thanks for your great lib.
I have used shared element for two screens, Lets say screen1 and screen2.
Now I want to navigate from Second one to the third screen. but don't want the shared transition to occur.
here is a screen recording:

![shared-element](https://user-images.githubusercontent.com/59901734/75383035-db212800-58f0-11ea-886d-f20cc66829dc.gif)

**Screen1 component code **
```
const LogoList = ({ navigation }) => {

    const { data } = useContext(DataContext);
    // console.log(value)

    return (
        <FlatList
            data={data}
            contentContainerStyle={styles.listCN}
            numColumns={2}
            renderItem={(data) => {
                return (
                    <View style={styles.itemCN}>
                        <SharedElement id={data.item.name}>
                            <TouchableOpacity style={styles.itemInner} onPress={() => navigation.navigate('Model', { name: data.item.name, image: data.item.image })}>
                                {/* <Text style={styles.item}>{data.item.name}</Text> */}
                                <Image style={styles.item} source={{ uri: data.item.image }} />
                            </TouchableOpacity>
                        </SharedElement>
                    </View>
                )
            }}
        />
    )
}
```

**Screen2 code:**
```
const ModelScreen = ({ navigation }) => {
    return (
        <View style={styles.container}>
            <SharedElement id={name}>
                <View style={styles.imageCN}>
                    <Image style={styles.image} source={{ uri: image }} />
                </View>
            </SharedElement>
            <Button title='year' onPress={() => navigation.navigate('Year')} />
        </View>
    )
}

ModelScreen.sharedElements = (navigation, other, showing) => {
    console.log(showing)
    const name = navigation.getParam('name');
    return [{
        id: name,
        // animation: 'fade',
    }];
};
```

**Screen3 code**
```

const YearScreen = () => {
    return (
        <View>
            <Text>Year Screen</Text>
        </View>
    )
}
```

How can I disable the shared element on 3rd screen? As it does not have anything to do with the previous page's transition.

**Comment by IjzerenHein** [comment]
Hi! Please have a look at this section in the readme:

> *Only transition when coming from a specific route*
>
> If you only want to show a transition when pushing from a particular screen, then use the route-name and showing argument.

```jsx
class DetailScreen extends Component {
  static sharedElements = (navigation, otherNavigation, showing) => {
    if ((otherNavigation.state.routeName === 'List') && showing) {
      const item = navigation.getParam('item');
      return [`item.${item.id}.photo`];
    }
  }
  ...
}
```

You can use the `otherNavigation` and `showing` params to decide whether you want a transition or not. Using `otherNavigation` you can get the route-name of the screen that you are navigating to or from.

In your case this would probably look like this:

```
ModelScreen.sharedElements = (navigation, otherNavigation, showing) => {
  if (otherNavigation.state.routeName === 'LogoList') {
    const name = navigation.getParam('name');
    return [{
        id: name,
        // animation: 'fade',
    }];
  }
};

**Comment by sa8ab** [comment]
Beautiful. thank you.
By the way do you know why stack navigator slows down when going 4 or 5 pages inside?
or the problem is from stack-navigator itself?
debugging is off and nothing is on the screens

**Comment by IjzerenHein** [comment]
Not sure. Are you using `react-native-screens` and have you called `enableScreens` ?
This will cause hidden screens to be removed from the view-hierarchy, freeing up resources for the OS. Especially when you have heavy screens with map-views you would start to notice a difference.

**Comment by sa8ab** [comment]
Yeah you're emazing, but now, first 2 are a bit slow and 3,4 & 5 work perfectly!!

**Comment by IjzerenHein** [comment]
Where are you testing this on? Can you share a video of the slow-down? Also, do you see a slow-down when not using shared-element transitions?

**Comment by sa8ab** [comment]
It is not that slow to be noticed on video, and yes. tested and problem is not because of the shared-element. seems to be with react-native-stack.
And thanks for your instant answer.

**Comment by IjzerenHein** [comment]
Closing this as the mentioned slow-down is not related to shared-element
