### ISSUE TITLE
sharedConfig not called

### ISSUE THREAD

**Issue by tobiaslins** [IjzerenHein/react-navigation-shared-element#3]
First of all: 
Thank you for creating this amazing library

I played around for about an hour now but couldn't get it to work.
Things I've done:
- Installed both libs
- pod install (RN 0.60, React Navigation 4)
- Recompiled app
- added shared navigator (it's nested in a Tab navigator maybe thats the problem?)
```js
 Exercises: createSharedElementStackNavigator(createStackNavigator, {
     Exercises,
     Exercise
 }),
```

- Added on both screens `Exercises` and `Exercise`
```js  
<SharedElement id="testing">
    <Text>{exercise.name}</Text>
</SharedElement>
```
- And finally added the `sharedElements` static method (also tried in both files)
```js 
Exercises.sharedElements = () => {
  console.log("i am here");
  return "testing"
};
```

Sadly I don't see anything changed. App runs as normal but no animations between the screens. Did I do anything wrong?

Thanks :)

**Comment by IjzerenHein** [comment]
Hey! Hmm that is weird indeed. Looking from your setup that should definitely have worked. If it's not calling the `sharedElements` function is probably due to the fact that it is not correctly detecting the route changes. I should probably add a verbose debug option to see what's going on here.
I made a basic example repo which shows a correct setup, could you perhaps have a look at that, maybe you can find a difference between your app and that app?
https://github.com/IjzerenHein/react-navigation-sharedelement-rn60demo

**Comment by tobiaslins** [comment]
@IjzerenHein I already checked multiple times the differences to your demo. Couldn't find one!
As said the only thing thats maybe different is the fact that I've nested it in a switch & tab navigator. 
I try to add `onNavigationStateChange` and see if everything gets triggered correctly there!

**Comment by IjzerenHein** [comment]
Well what I would do in your case, is try and repro it with the smallest app possible. In this case what would probably mean to add a switchNavigator to the RN60 demo and see whether that causes the problem. I don't think so though cause I also have a switch and tab-navigator in my app, and it works for me.
Perhaps also try deleting node_modules and your yarn.lock to ensure you're really using the same deps. And also perform a `yarn start --reset-cache`

**Comment by tobiaslins** [comment]
@IjzerenHein I finally found the problem.

I was using `react-navigation-stack@2` instead of `react-navigation-stack@1.5`
I downgraded the version and it was working :)

I'll investigate if it's a bug of their alpha or if we need to adapt something to support it in the future!

Thanks!

**Comment by IjzerenHein** [comment]
Ah that explains it. Yeah v2 is still in alpha and things like certain lifecycle events are not working correctly with that yet
