### ISSUE TITLE
TypeError: Object is not a Function (Near '.... createNavigator...)

### ISSUE THREAD

**Issue by BadMask121** [IjzerenHein/react-navigation-shared-element#30]
Im currently running 

React-native v0.61.5
react-navigation: v4

**Comment by IjzerenHein** [comment]
Can you share more info?
Which version of react-navigation-stack are you using?
And how are you calling `createSharedElementStackNavigation`?

**Comment by BadMask121** [comment]
I've fixed it, I was using a much older version.

Thank you
