### ISSUE TITLE
Rendering interstitial loading views causes issues

### ISSUE THREAD

**Issue by tberman** [IjzerenHein/react-navigation-shared-element#4]
Sorry, this is going to be a long one, and if the response is 'please come back with an example of the issue because your explanation is not good enough to follow/fix' that is fine.

We have an app that uses relay under the hood, and in a couple places we want to use a shared element style animation between screens. In order to do that, the way our app works is it navigates to a screen that uses the main component itself as a 'loading component' with dummy data from the original location while it loads from the network the data it needs to completely render.

When that data fetch takes longer than the animation, everything works great.

However, when that data fetch is faster than the animation (easy to see using slow animations in the simulator), you end up with the re-render causing the formerly 'hidden' components appearing during the animation.

Not a huge issue and I know what we are doing is a bit strange, but likely to be a common pattern.

Any thoughts on the right way to approach this issue?

**Comment by IjzerenHein** [comment]
Hi Todd. I’m not sure I follow exactly how you implemented this. Can you maybe write it down as a list of relevant steps that take place?

Couple questions:
- When the loading finishes, do you just hide the main component, or navigate/replace to a new route?
- Can you share videos of it when it works correctly, and when it fails?
