### ISSUE TITLE
Won't work with createMaterialTopTabNavigator. bug

### ISSUE THREAD

**Issue by EmmanuelID** [IjzerenHein/react-navigation-shared-element#40]
The transition does not work correctly in createMaterialTopTabNavigator, in the first tab screen with stackNavigator it works fine, but in the second one it doesn't work anymore.

**Comment by IjzerenHein** [comment]
Can you share a video demonstrating the problem?

**Comment by EmmanuelID** [comment]
Yes, I share the link
[https://drive.google.com/file/d/1m24w7lfZf9oAVlJEeEJWsd0vB8JhXzVc/view](url)

**Comment by IjzerenHein** [comment]
Awesome, thanks!

**Comment by IjzerenHein** [comment]
Hi! I've been working on a fix for this. It seems that the `MaterialTopTabNavigator` translates its entire content and this causes the positioning algorithm to calculate the start- and ending coordinates incorrectly. This is therefore a native problem and I'm working on an update to `react-native-shared-element`.

**Comment by IjzerenHein** [comment]
I've released a new version of react-native-shared-element, v0.7.0. This fixes the MaterialTopTabNavigator bug on iOS:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.7.0
