### ISSUE TITLE
maximum update depth exceeded error, when changing from createStackNavigator to createSharedElementStackNavigator

### ISSUE THREAD

**Issue by jithinlal** [IjzerenHein/react-navigation-shared-element#41]
I am getting a maximum update depth error when using createSharedElementStackNavigator, this is not seen when using createStackNavigator.[](url)
<img width="412" alt="Screen Shot 2020-03-20 at 3 45 07 PM" src="https://user-images.githubusercontent.com/9658385/77154617-0fd46980-6ac2-11ea-9c6a-abbab2cadfcc.png">

**Comment by IjzerenHein** [comment]
Please share an example (https://snack.expo.io/) that reproduces this problem.
