### ISSUE TITLE
[v5] typo in Readme

### ISSUE THREAD

**Issue by troublediehard** [IjzerenHein/react-navigation-shared-element#46]
I suppose `id` should be the same. 

<img width="658" alt="Screenshot 2020-03-29 at 22 59 20" src="https://user-images.githubusercontent.com/6594232/77859283-1fb22300-7211-11ea-91c7-d4a7c9f64901.png">

**Comment by IjzerenHein** [comment]
Hi, thanks for reporting. Could you submit a PR for that? It's really easy, just go to the file and click to pencil:

![image](https://user-images.githubusercontent.com/6184593/77892943-9f70d980-7273-11ea-8a08-dcb1b9ef3711.png)

Thanks!

**Comment by troublediehard** [comment]
@IjzerenHein yep, I'll do it. I just wasn't sure 100% that I'm right.

**Comment by IjzerenHein** [comment]
That's okay. PRs will be reviewed anyway, so if it's inaccurate I would let you know; and otherwise I can just immediately merge it 👍
