### ISSUE TITLE
Typescript error: Property 'router' is missing in type 'ComponentClass<any, any>' 

### ISSUE THREAD

**Issue by jay-jlm** [IjzerenHein/react-navigation-shared-element#48]
After replacing createStackNavigator with createSharedElementStackNavigator I get the following typescript error(s)

```
const AppNavigator: React.ComponentType<any>
Argument of type 'ComponentType<any>' is not assignable to parameter of type 'NavigationNavigator<unknown, unknown>'.
  Type 'ComponentClass<any, any>' is not assignable to type 'NavigationNavigator<unknown, unknown>'.
    Type 'ComponentClass<any, any>' is not assignable to type 'ComponentClass<NavigationNavigatorProps<unknown, {}, unknown>, any> & { router: NavigationRouter<unknown, {}>; navigationOptions?: unknown; }'.
      Property 'router' is missing in type 'ComponentClass<any, any>' but required in type '{ router: NavigationRouter<unknown, {}>; navigationOptions?: unknown; }'.ts(2345)
react-navigation.d.ts(229, 3): 'router' is declared here.
```

Dependencies:
    "react-navigation": "^4.3.5",
    "react-navigation-shared-element": "^2.2.0",
    "react-navigation-stack": "^2.3.9"

Code:

````
const AppNavigator = createSharedElementStackNavigator(
  {
    Home: {
      screen: HomeScreen,
    },
    History: {
      screen: HistoryScreen,
    },
  },
  {
    initialRouteName: 'Home',
    headerMode: 'none',
    defaultNavigationOptions: {
      ...TransitionPresets.FadeFromBottomAndroid,
    },
  },
);

export default createAppContainer(AppNavigator);
```

**Comment by jay-jlm** [comment]
Also, I have been looking at the `/example` folder and strangely enough everyone I looked at uses vanilla `createStackNavigator` as opposed to  `createSharedElementStackNavigator `, so that was a bit confusing.

**Comment by IjzerenHein** [comment]
> Also, I have been looking at the /example folder and strangely enough everyone I looked at uses vanilla createStackNavigator as opposed to createSharedElementStackNavigator , so that was a bit confusing.

Yeah the app in ./example was actually from another repo and was still on my todo list to update. I've just updated that and it now has proper examples and provides a platform for adding tests and demos

**Comment by IjzerenHein** [comment]
I just released an update, this issue should be fixed in:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.3.0

Let me know whether it has been resolved for you.
