### ISSUE TITLE
Shared element animates when going forward but not when going back

### ISSUE THREAD

**Issue by jay-jlm** [IjzerenHein/react-navigation-shared-element#49]
Happens on my latest project, I am not passing any dynamic parameters, instead I hardcoded the shared element id the return value of the `DetailScreen.sharedElements` function for simplicity.

The sharing transition can be seen when navigating from Home to Detail, but when navigating back using the back button on Android, the sharing is not performed.

```
    "react-navigation": "^4.3.5",
    "react-navigation-shared-element": "^2.2.0",
    "react-navigation-stack": "^2.3.9"
```
Is this expected behavior?
If not, any hints on what could be causing this issue?

**Comment by jrmartinez96** [comment]
Same here with iOS :(

**Comment by jrmartinez96** [comment]
Follow the instructions from the branch "navigation-v5" of this repository. I tried it and it works fine for me.

**Comment by jay-jlm** [comment]
@jrmartinez96  I stuck with V4 though. I looked around and did not find anything in the V5 branch docs that seemed to be relevant to my scenario.

**Comment by bcgilliom** [comment]
I'm getting the same problem on r-nav v4, rn .59, stack nav 2

**Comment by bureyburey** [comment]
having  the same issue as well.
expo SDK 36 (uses react-native 0.61.4)
react-navigation 4.3.7
react-navigation-stack 2.3.11

one thing i did notice is this:
on iOS simulator, if i swipe right to left (to go back) whilst in transition to the new route, it does work, and same when clicking the <kbd>back</kbd> button on android.

but once the transition to the new screen is completed, going back to previous screen produces a regular navigation transition.

**Comment by ghondar** [comment]
same here using:

react-native 0.62.2
react-navigation 4.0.0
react-navigation-stack 2.3.11
react-navigation-shared-element 2.2.0
react-native-shared-element 0.6.1

**Comment by IjzerenHein** [comment]
Hi! It seems some things were changed in recent react-navigation/stack releases which broke the back navigation (some lifecycle events were changed).
I've just released a new version which should fix this:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.3.0

Let me know whether that resolves your problem!

**Comment by bureyburey** [comment]
@IjzerenHein working  beautifully now!

many thanks for the fix :)))

keep it up!

**Comment by vitosorriso** [comment]
Hello everyone! i was facing the same problem after trying to merge my fully working branch with animation (untouched in the last 2-3 weeks) inside development branch. Even fixing versions to some potential-putting-issues library (also react-navigation-stacks) was still breaking my animation. After upgrading this library to 2.3.0, i also fixed the problem! Thanks so much @IjzerenHein
