### ISSUE TITLE
Transition effect only on particular screen navigation

### ISSUE THREAD

**Issue by vikrantnegi** [IjzerenHein/react-navigation-shared-element#5]
Hi,

Thank you for creating this awesome package.

I have a question regarding keeping the transition enable only when navigating to a particular screen and keeping the default navigation for other screens.

I'm trying to mimic something like Microsoft **To Do** app. 

See below gif where the transition is only when we navigate to the setting by clicking on **Header** and not when we navigate to the todo items. 
Is this possible or do you recommend some specific way to achieve this?

![Todo](https://user-images.githubusercontent.com/3294287/65302063-90f48780-db97-11e9-8730-1be75e240382.gif)

Thanks.

**Comment by IjzerenHein** [comment]
Hi, in that case I would define the ‘sharedElements’ static function on the screen that you are navigation to. And then you can additionally filter on the route-name that you are coming from. Like this:

```
class MyAccountScreen extends Component {
  static sharedElements = (navigation, otherNavigation, showing) => {
    if ((otherNavigation.state.routeName === “Overview'” && showing) {
      return [“fullName”, “emailAddress”, “userPhoto”];
    }
  }

  ...
}
```

**Comment by vikrantnegi** [comment]
@IjzerenHein 
What if I `Header` component for the header with the name, email, and photo? 
Can I add the `SharedElement` tag inside `Header` component that is being used in the two screens?

**Comment by IjzerenHein** [comment]
Transitioning to and from the Header has not yet been explored yet. It probably doesn’t work, but I would like to support it in the future.
