### ISSUE TITLE
Parent screen still clickable during transition

### ISSUE THREAD

**Issue by yolpsoftware** [IjzerenHein/react-navigation-shared-element#52]
Not sure if the problem is with `react-navigation-shared-element`, but we currently have the situation that during the transition from Screen1 to Screen2, the elements of Screen1 are still clickable. So if the user presses two navigating buttons fast enough, then two `navigate()` calls are issued at the same time.

If this is not related to `react-navigation-shared-element`, we would be grateful for a hint about the cause of this behavior.

Versions:

```
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-shared-element": "^0.5.5",
    "react-navigation": "^4.1.0",
    "react-navigation-shared-element": "^1.0.0",
    "react-navigation-stack": "~1.10.3",
```

Happens on iOS. Not sure about Android.

**Comment by IjzerenHein** [comment]
You should post this question in the react-navigation repo.

**Comment by yolpsoftware** [comment]
But the transition is done via `react-navigation-shared-element` (`createSharedElementStackNavigator`). As I understand it, you do that using an overlay which shows the animation.

It seems that this overlay is transparent for touch events, i.e. during the transition, touch events are handled by the underlying view, and not by the transition overlay.

**Comment by IjzerenHein** [comment]
That's correct, the overlay has `pointer-events` none.
https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/src/SharedElementRendererView.tsx#L33
