### ISSUE TITLE
Followed the example given but animation seems to be slightly off

### ISSUE THREAD

**Issue by hannzern** [IjzerenHein/react-navigation-shared-element#53]
I followed the example code given in the docs under the "Basic Usage" and the animation I'm able to achieve is below with a slight delay of the image being shown from the prev page:-

BEFORE NAVIGATION
<img width="464" alt="Screenshot 2020-04-04 at 4 27 53 PM" src="https://user-images.githubusercontent.com/49383330/78422379-65e40800-7691-11ea-8f46-bec401030377.png">

AFTER NAVIGATION
<img width="471" alt="Screenshot 2020-04-04 at 4 28 01 PM" src="https://user-images.githubusercontent.com/49383330/78422387-78f6d800-7691-11ea-8c1c-a0761a0d6d52.png">

HALF SECOND AFTER NAVIGATION STOPPED
<img width="468" alt="Screenshot 2020-04-04 at 4 28 02 PM" src="https://user-images.githubusercontent.com/49383330/78422400-8ad87b00-7691-11ea-9fde-0e3031007675.png">

**Comment by IjzerenHein** [comment]
Hi. Can you please provide a video recording or animated gif demonstrating the problem?
