### ISSUE TITLE
Doesn't work with ScrollView on destination screen

### ISSUE THREAD

**Issue by mi5ha** [IjzerenHein/react-navigation-shared-element#54]
When destination screen has ScrollView, shared element doesn't scroll as it should.

I already have custom transitionSpec set, and it doesn't help.

react-navigation@4.2.2
react-navigation-stack@2.2.3
react-native-shared-element@0.5.6
react-navigation-shared-element@2.1.0

![ScrollView-problem-2](https://user-images.githubusercontent.com/1238203/78776728-a0eb8180-7998-11ea-9ce6-2dffc52c9f0c.gif)

**Comment by 24dev** [comment]
Already an open issue, maybe you can find help there: https://github.com/IjzerenHein/react-navigation-shared-element/issues/43

**Comment by mi5ha** [comment]
No, no help there

**Comment by IjzerenHein** [comment]
Hi! This is a curious problem. Could you add a test-case to the app in `./example`, and then I can take a look.

**Comment by mi5ha** [comment]
> Hi! This is a curious problem. Could you add a test-case to the app in `./example`, and then I can take a look.

I tried to replicate the bug in example project, but I could not! It works perfectly there.

I see that example is using newer versions of everything, so maybe thats the issue, will report when I try it.

![Apr-21-2020 10-15-42](https://user-images.githubusercontent.com/1238203/79842435-1c95f700-83b9-11ea-9d71-c04f3f41490b.gif)

**Comment by mi5ha** [comment]
I installed the newest versions of everything and now it works!

![shared2](https://user-images.githubusercontent.com/1238203/80306017-dc6fb380-87c0-11ea-96f7-f0c27072a32e.gif)

react-navigation@4.3.8
@react-navigation/core@3.7.5
react-navigation-drawer@2.4.12
react-navigation-material-bottom-tabs@2.2.11
react-navigation-shared-element@2.3.0
react-navigation-stack@2.3.13
react-navigation-tabs@2.8.12
react-native-shared-element@0.7.0
react-navigation-shared-element@2.3.0

**Comment by timorss** [comment]
Try set gestureEnabled to false
