### ISSUE TITLE
[v5] Buggy animations when moving back fast (with screenshots, demo app)

### ISSUE THREAD

**Issue by jonmountjoy** [IjzerenHein/react-navigation-shared-element#57]
Thank you for this magic, and the alpha of the v5 support (https://github.com/IjzerenHein/react-navigation-shared-element/issues/2#issuecomment-600856198) !

Bug: When you navigate from a detail screen back to the list screen within about a second, and then back again, the shared element is rendered without any animation.  There also seems to be a weird pause after animating.

Demo app: https://github.com/jonmountjoy/react-native-shared-element-navigation-demo

You can see the problem here:

![](https://github.com/jonmountjoy/react-native-shared-element-navigation-demo/raw/master/assets/clean.gif)

Here it is again, without using a fade animation. You'll see an odd pause.

![](https://github.com/jonmountjoy/react-native-shared-element-navigation-demo/raw/master/assets/fuzz.gif)

Bedankt!

**Comment by sa8ab** [comment]
Same issue +1

**Comment by IjzerenHein** [comment]
Hi! This seems to be related to #24
Please try the proposed solution in https://github.com/IjzerenHein/react-navigation-shared-element/issues/24#issuecomment-599215880

**Comment by jonmountjoy** [comment]
I can confirm this works, thank you @IjzerenHein .

In React Navigation 5 syntax, it looks a bit like this:

```
<Stack.Navigator
      headerMode="none"
      screenOptions={{
        transitionSpec: {
          open: {
            animation: "timing",
            config: {
              duration: 350
            }
          },
          close: {
            animation: "timing",
            config: {
              duration: 350
            }
          }
        }
      }}
    >
      <Stack.Screen name="ListSubscribedDecks" component={ListSubscribedDecks} />
      .....
</Stack.Navigator>
```
