### ISSUE TITLE
[v5] [Android] Bug when going back from the screen that hides bottomTabNavigator

### ISSUE THREAD

**Issue by phamhoaivu911** [IjzerenHein/react-navigation-shared-element#59]
Hi @IjzerenHein, first thank you for your awesome library.

I have this issue with **react-navigation v5** and **only on Android**. It may be related to issue #42. When I go back from a screen that hides the bottom tab navigator, it seems that the bottom tab affects the size of the original image and its position. 

This is the gif image of the issue

<img src="https://user-images.githubusercontent.com/4929170/77673197-71ae3b00-6fbc-11ea-88f8-7cf16e5c7055.gif" width="300" />|
:-:|

This is the repository to reproduce the issue: https://github.com/phamhoaivu911/RNSE_example

Any help would be much appreciated. Please let me know if there's anything I can do to help. Thank you!

**Comment by phamhoaivu911** [comment]
According to this document https://reactnavigation.org/docs/hiding-tabbar-in-screens/. Issue #42 is because we were hiding the bottom tab the wrong way. 

After following this guide to put the bottomTabNavigator inside the StackNavigator, the transition seems to work well.

The only thing is that if we jump to another tab, the transition does not work anymore. The workaround is to wrap the screen component of the bottomTab inside another stackNavigator.

If anyone has this issue, please follow this branch for the workaround https://github.com/phamhoaivu911/RNSE_example/tree/fix_v5

**Comment by Waheed-Rumaneh** [comment]
i was have the same problem and i research so much to solve it
i tried so many solutions but nothing worked

finally i solve it and this is the solution that worked for me if you want try it
just add this in DetailScreen option :

options={{ ...TransitionPresets.FadeFromBottomAndroid, }}

this will prevent the shared element default animation that make this bug when close the page from Top to Bottom ,
**_but the custom back button will not fixed you can use the back button from Device or Swipe the page down_** 

you can import it from @react-navigation/stack :
import { createStackNavigator, TransitionPresets } from '@react-navigation/stack';
