### ISSUE TITLE
Nested createSharedElementStackNavigator()'s don't work

### ISSUE THREAD

**Issue by anfen** [IjzerenHein/react-navigation-shared-element#6]
I'm not sure if this is supposed to be possible, but would be great if so

**Comment by IjzerenHein** [comment]
Yes, we should be able to get that to work. Thanks for the reminder :)

**Comment by sa8ab** [comment]
What suggestion do you have on solving this issue before you update the lib?
Can we make shared element stack as top level?

**Comment by IjzerenHein** [comment]
I don't have a suggestion tbh. In this case it's just a matter of having a reproducible case and diving in the code and debugging where it goes wrong. If you want to help, having a very simple example that reproduces the problem would be helpful.

**Comment by IjzerenHein** [comment]
Hi. I've begun work on v2 of this lib, which will work with react-navigation-stack@2. I have nested navigators  working in that version. If you are interested in testing, please take a look here:
https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/README_v2.md

**Comment by IjzerenHein** [comment]
Support for stack v2 and nested navigators has been released.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.0.1

Let me know whether this fixes the problem for you.

**Comment by IjzerenHein** [comment]
Closing
