### ISSUE TITLE
Items inside shared element are not clickable

### ISSUE THREAD

**Issue by ginold** [IjzerenHein/react-navigation-shared-element#63]
Hi,

my setup is pretty basic: I click on a <SharedElement => image> that goes to a detail view with the same image. The transition occurs correctly but the item inside does not receive any clicks even when wrapped in a `<Touchable>`. I'd like to make an Instagram-style change of image URL when clicking on the image to load the next image.

In fact, this DOES work on PC when i drag the Detail Screen just a little bit as if i were to swipe it away, then i let it go and  the view seems to reload quickly and the clicks are received. Sounds like a problem with react-navigation, don't know.

**Comment by IjzerenHein** [comment]
I don't understand what you're trying to achieve. Please report a proper bug report, preferably with a reproduction test-case in the `./example` app
