### ISSUE TITLE
Type error evaluating AnimationContext.Consumer

### ISSUE THREAD

**Issue by Stevemoretz** [IjzerenHein/react-navigation-shared-element#64]
Using the latest version on expo sdk 36 I get this error.
 

>    "react-navigation-shared-element": "^2.3.0",
>     "react-native-shared-element": "~0.5.1",
>

The error is located in /node_modules/react-navigation-shared-element/build/createSharedElementScene.js on line 65 AnimationContext.Consumer.

I've tested all the other versions until version 1.0.0 even 2.0.0 alpha didn't work the only version that doesn't give me this error is version 1.0.0 which is too old.

**Comment by Stevemoretz** [comment]
It had issues with my react navigation versions but now it works. Border Radius didn't get animated so that's why I update.And it still doesn't animate.so that was waste of time.

**Comment by loicboyeldieu** [comment]
Did you find a way to fix it?
