### ISSUE TITLE
Shared element View with child elements is buggy [v5]

### ISSUE THREAD

**Issue by nemanjaciric** [IjzerenHein/react-navigation-shared-element#69]
First of all, amazing library! Not sure if it is possible to have shared view with child view? I have this buggy animation on the child view which stays the same. I couldn't find any related issue. Is it possible to have child elements on parent View?

First screen:
```
const SharedElements = ({ navigation }) => {
    return (
        <>
            <SharedElement id={`view`}>
                <View style={styles.container}>
                    <TouchableOpacity
                        onPress={() => navigation.push("SecondScreen")}
                    >
                        <View style={styles.innerContainer} />
                    </TouchableOpacity>
                </View>
            </SharedElement>
        </>
    );
};

const styles = StyleSheet.create({
    container: {
        width: 150,
        height: 150,
        backgroundColor: "red",
        justifyContent: "center",
        alignItems: "center",
    },
    innerContainer: {
        backgroundColor: "blue",
        width: 50,
        height: 50,
    },
});
```
Second screen:
```
const SecondScreen = ({ route, navigation }) => {
    return (
        <View style={styles.container}>
            <SharedElement id={`view`}>
                <View style={styles.containerShared}>
                    <View style={styles.innerContainer} />
                </View>
            </SharedElement>
        </View>
    );
};

const styles = {
    containerShared: {
        width: 150,
        height: 250,
        backgroundColor: "red",
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center",
    } as ViewStyle,
    innerContainer: {
        backgroundColor: "blue",
        width: 50,
        height: 50,
    },
};
```
App.js:
```
const interpolator = ({ current: { progress } }) => {
    return { cardStyle: { opacity: progress } };
};

export default function App() {
    return (
        <NavigationContainer>
            <Navigator>
                <Screen name="FirstScreen" component={FirstScreen} />
                <Screen
                    name="SecondScreen"
                    component={SecondScreen}
                    options={{
                        cardStyleInterpolator: interpolator,
                    }}
                    sharedElementsConfig={(route, otherRoute, showing) => {
                        return [
                            {
                                id: "view",
                                animation: "move",
                            },
                        ];
                    }}
                />
            </Navigator>
        </NavigationContainer>
    );
}
```
![ezgif-6-f14e88295adc](https://user-images.githubusercontent.com/42605307/80314039-0dff7380-87ef-11ea-9d2c-8ae80f99591b.gif)

**Comment by DaveClissold** [comment]
What you are seeing is the transition stage, where the whole of the shared element is being resized, then when the inner element snaps back is when the second screen has finished rendering. I have a similar situation with an image and a background, because the background resized to a different ratio than the image I had a similar problem.

Have you tried wrapping the inner element as another shared element?  

```
<SharedElement id={`view`}>
  <View style={styles.containerShared}>
    <SharedElement id={`view2`}>
      <View style={styles.innerContainer} />
    </SharedElement>
  </View>
</SharedElement>
```

**Comment by mcarlier09** [comment]
I think it's not a bug but the resize of the element from one screen to an other may be streching.
 Did you tried to add a resize option in you sharedElementsConfig ?
  `  {
                                id: "view",
                                animation: "move",
                                resize:'none',
                            },`

**Comment by DaveClissold** [comment]
What you are seeing is the transition animation between first screen and second screen.  Think of the flow like this

First screen -> Transition -> Second Screen

The second screen rendered when the transition has finished but the transition remains for a brief moment to allow the second screen to render properly.

The animation is showing the resizing of the outer View with the inner view in relation to the height, width ratio of the outer element, which different between first and second screen, first screen the ratio is 1:1, second the ratio is 1:1.66667. The jump to normal size is when the second screen has rendered.

The inner View needs to be wrapped into it's own shared element, then it will retain it's dimensions between the 2 screen.

```
<View style={styles.container}>
            <SharedElement id={`viewOuter`}>
                <View style={styles.containerShared}>
                    <SharedElement id={`viewInner`}>
                        <View style={styles.innerContainer} />
                    </SharedElement>
                </View>
            </SharedElement>
        </View>
```

**Comment by nemanjaciric** [comment]
@mcarlier09 Tried, but then I can't have animation when navigating.
@DaveClissold Already tried that and the gif shows the result. Inner view will be stretched even if it is shared.

**Comment by IjzerenHein** [comment]
You will need to separate the views so that there is no parent/child relationship between them. The way shared-element works, is that it takes a snapshot of the view and then it can cheaply animate it on the screen. This snapshot will therefore always contain the rendered pixels of all its children as well. When changing the size, the whole thing will the stretched to the new size.

```js
// Background
<SharedElement style={styles.backgroundContainer}>
  <View style={styles.background} />
</SharedElement>

...

// Foreground elements
<View style={StyleSheet.absolutePosition}>
  <SharedElement>
    <View />
  </SharedElement>
</SharedElement>
```

**Comment by alexandreh92** [comment]
I'm having the same issue!

@nemanjaciric did you manage to solve this?

**Comment by nemanjaciric** [comment]
@alexandreh92 No. Accordingly to the previous comment from @IjzerenHein it is not possible to do things in the way I wanted to. You can do that with two absolute Views if that suits you. In my case it didn't.
