### ISSUE TITLE
Getting transition progress.

### ISSUE THREAD

**Issue by MikkelSnitker** [IjzerenHein/react-navigation-shared-element#7]
Hi.

Is it possible to get the progress of the transition? 
I would like my "details" screen to do some custom animation that follows the sharedelement's transition.

Hope it makes sense :)

/Mikkel

**Comment by IjzerenHein** [comment]
Hi!

The shared-element transition uses the Animated.Value from the stack-navigator. My first impression is that I do not deem it the responsibility of the shared-element lib to expose it. Instead you should access it through the transition-props in the Stack-navigator API.
