### ISSUE TITLE
Setting the animation order

### ISSUE THREAD

**Issue by jrounsav** [IjzerenHein/react-navigation-shared-element#70]
I'm trying to leverage this package to recreate some of the shared element transitions from the material design motion system
https://material.io/design/motion/the-motion-system.html#container-transform

The demos on the material site fade-out the starting element, and then fade-in the ending element after the first fade-out completes. I've been trying to find a way to do that with RNSE but everything I try has the animations starting at the same time (my pages only share the container element, while the content is distinct between the two) so there is a point in the transition where a lot of clutter is visible on-screen.

Is ordering the animations possible, or are there any plans to allow for this?

**Comment by IjzerenHein** [comment]
Doing these kinds of full-scene transitions is not supported. Perhaps in the future, if it's feasible to do.

You can definitely order elements though and also perform fade-in and fade-out effects for elements that are not shared between screens. The order of the elements returned in the `sharedElements` function is also the ordering that they are drawn on the screen. Additionally, when you return an id to an element that exists only on one of the screens, then it will automatically fade-in/out that element.

**Comment by jrounsav** [comment]
Thank you for the info!
+1 great library
