### ISSUE TITLE
[v5 android] SharedElement stays stuck in place when navigator goes back

### ISSUE THREAD

**Issue by geooot** [IjzerenHein/react-navigation-shared-element#72]
First, thanks for a great library! It doesn't seem like there is much else like this. I just wanted to let you know that on Android the transition going back makes the SharedElement stick to the screen (video demo: https://streamable.com/saadz5). This seems to only happen on android.

The setup I have is some cards in a FlatList (for the home screen), where each card is a shared element. When a card is pressed it navigates to a detail screen with the same card at the top and some more content underneath it (the detail screen has a scroll view).

Versions:
```
"react-native-shared-element": "^0.7.0",
"react-navigation-shared-element": "^5.0.0-alpha1",
"@react-navigation/native": "^5.3.0",
"@react-navigation/stack": "^5.3.3",
```

React Native Info:
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 84.35 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by wzahedi** [comment]
This exact same issue happens on iOS if I navigate back and try to press the image again too quickly. It does not get stuck if i wait a little before pressing it again. This seems to be a pretty big issue if its on both platforms. Any help appreciated!

**Comment by geooot** [comment]
@wzahedi In the meantime, I am only enabling the animation when opening the page (using `sharedElementsConfig`)
```jsx
<Stack.Screen
    name="Detail"
    component={DetailScreen}
    sharedElementsConfig={(route,_,showing) => {
        const {details} = route.params;
        // only do shared element transition when a new screen is shown
        if (showing) {
            return [
                {
                    id: `Card::${details.id}`,
                    animation: 'fade',
                },
            ];
        } else {
            return [];
        }
    }}
/>
```

**Comment by wzahedi** [comment]
@geooot I tried that but it still has the issue unfortunately. Detailed here:
https://github.com/IjzerenHein/react-navigation-shared-element/issues/24#issuecomment-631916205

**Comment by geooot** [comment]
@wzahedi 
Changing the transitionSpec to use timing instead of spring actually worked work me. Now the card doesn't stick

```tsx
<Stack.Screen
    name="Detail"
    component={DetailScreen}
    options={{
        headerShown: false,
        animationEnabled: true,
        gestureEnabled: Platform.OS === 'android',
        transitionSpec: {
            open: {
                animation: 'timing',
                config: {
                    duration: 250,
                },
            },
            close: {
                animation: 'timing',
                config: {
                    duration: 250,
                },
            },
        },
        gestureDirection: 'vertical',
        gestureVelocityImpact: 0.5,
        cardStyle: {backgroundColor: 'transparent'},
        cardOverlayEnabled: true,
        gestureResponseDistance: {
            vertical: 100,
        },
    }}
    sharedElementsConfig={(route): SharedElementConfig[] => {
        const {details} = route.params;
        return [
            {
                id: `MissionCard::${details.id}`,
                animation: 'fade',
            },
        ];
    }}
/>
```

**Comment by wzahedi** [comment]
Thanks, I changed it to timing but had to lower the duration to 100. Unfortunately this will have to do for now.

**Comment by mrmarktyy** [comment]
I had the exact problem on Android. 
The fix for me is to lower the duration from 600 to something like 300.

**Comment by ismaelbarry** [comment]
I tried the same exact solution above regarding altering the transitionSpec. However, I'm still running into the same problem with the SharedElement staying stuck in place while scrolling through a FlatList. 

`const DiscoverTabStack = createSharedElementStackNavigator(
  createStackNavigator,
  {
    Discover: { screen: DiscoverScreen, path: "discover" },
    DetailedActivity: DetailedActivityScreen,
  },
  {
    animationEnabled: true,
    gestureVelocityImpact: 0.5,
    cardOverlayEnabled: true,
    gestureResponseDistance: {
      vertical: 100,
    },
    defaultNavigationOptions: {
      transitionSpec: {
        open: {
          animation: "timing",
          config: {
            duration: 100,
          },
        },
        close: {
          animation: "timing",
          config: {
            duration: 50,
          },
        },
      },
    },
  }
);`


Currently, I'm using the following versions:
- "react-native-shared-element": "^0.7.0"
- "react-navigation-shared-element": "1"
- "react-navigation-stack": "^1.10.3"
-  "react-navigation-tabs": "^2.6.2"
- "react-navigation": "^4.0.10"
-  "react-native-screens": "~2.15.0"

Anyone know what the problem may be?
