### ISSUE TITLE
Screen.sharedElements not triggering

### ISSUE THREAD

**Issue by linusnyren** [IjzerenHein/react-navigation-shared-element#75]
Hi!
Im trying to get this to work but the animations is not working at all, its just the regular transition.
my console log in sharedElements function isnt triggering which might be the problem?
Here is my components

here is the parent
`<SharedElement id={data.title}>  
        <Image style={styles.imageBackground} source={data.images[0] ? {uri:data.images[0].url} : require('../../assets/images/mr_Chair.png')} />  
    </SharedElement>   
`

and the child with the sharedElements function
`                <SharedElement id={rentalItemObject.title}>  
                    <Image style={styles.imageStyle} source={{uri:rentalItemObject.images[0].url}}/>  
                </SharedElement>`

heres the shredElements function
`RentItemScreen.sharedElements = (navigation, otherNavigation, showing) => {
    const item = navigation.state.params.data
    console.log(item)
    return [item.title];
  };`
my stacknavigator
`const HomeStack = createSharedElementStackNavigator4(
  {
    Home: HomeScreen,
    RentItem: RentItemScreen,
    ItemMap:  LocationMap,
    SellerScreen: SellerScreen,
    UpdateItem: UpdateItem,
  },
  config,
  {
    name: 'Homestack',
    debug: true
  }
);`

the versions i'm using is
`    "react-navigation-shared-element": "^3.0.0",
    "react-navigation-stack": "^2.0.0",
"react-navigation": "^4.3.7",`

**Comment by IjzerenHein** [comment]
Hi! It seems you're using the new 3.x version of react-navigation-shared-element which hasn't been officially released yet.

At first glance your setup looks okay, but the `navigation` and `otherNavigation` arguments in the `sharedElements` function have changed to route arguments. Perhaps that's where the problem is. See the [migration guide](https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/docs/Migration.md).

Do you also have this problem when using the the latest v2 release ?

**Comment by linusnyren** [comment]
Hi! thanks for your reply! I got it working now by downgrading to 2.3.0!
Thank you!

**Comment by IjzerenHein** [comment]
Whoops, it seems that I accidentally pushed the new 3.x version to the latest release channel on npm 😬 My bad. I've reverted it and 2.3.x is now the latest on NPM again.

Still, I'm a bit curious why your code didn't work, it might be a hidden problem I am unaware of.

@linusnyren were you seeing that the `console.log` in this code was being called?

```
RentItemScreen.sharedElements = (navigation, otherNavigation, showing) => {
  const item = navigation.state.params.data;
  console.log(item);
  return [item.title];
};
```

**Comment by linusnyren** [comment]
That might explain it :D.
When i  were on the 3.x version it didnt console.log but when i reverted back to 2.3.0 and changed to the code below it just started working right away!

RentItemScreen.sharedElements = (route, otherRoute, showing) => {
    if((otherRoute.state.routeName=="Home") && showing){
        return [
            {id:route.state.params.data.id.toString()},
            {
                id:route.state.params.data.title,
                animation: 'fade',
                resize: 'clip' 
            }
        ];
    }
    
  };

**Comment by IjzerenHein** [comment]
Interesting. How does the rest of you navigation setup look like? Do you have additional navigators (tabs, modal) and nested navigators?
