### ISSUE TITLE
Unable to resolve module `react-navigation-stack` from `node_modules/react-navigation-shared-element/build/v4/createSharedElementStackNavigator.js`

### ISSUE THREAD

**Issue by mrousavy** [IjzerenHein/react-navigation-shared-element#79]
I'm getting the following error: Unable to resolve module `react-navigation-stack` from `node_modules/react-navigation-shared-element/build/v4/createSharedElementStackNavigator.js`.

![Simulator Screen Shot - iPhone 11 - 2020-05-29 at 15 22 01](https://user-images.githubusercontent.com/15199031/83265030-3b11be00-a1c1-11ea-9dcf-45addc7a5c4e.png)

I've noticed that it uses the `v4` directory even though I'm using react-navigation v5, is that normal?

`package.json`:

```json
"react-native-shared-element": "^0.7.0",
"react-navigation-shared-element": "^3.0.0",
"@react-navigation/native": "^5.5.0",
"@react-navigation/stack": "^5.4.1",
```

**Comment by IjzerenHein** [comment]
You're using the v3 prerelease version. It still has a couple issues, mainly with both the react navigation v4 and v5 dependency being required to be installed. As a temporary workaround you can install the react-navigation 4 (and stack 2) as dependencies. They won't be used but it will fix the import issue.

**Comment by mrousavy** [comment]
I see, is the prerelease v3 "newer" than the v5 branch? because I had no issues on the v5 branch, I'm guessing that's going to be discontinued though..?

**Comment by IjzerenHein** [comment]
Yes the v5 branch has been merged into the master branch. The v5-branch will indeed be discontinued (not much development went on there after its initial release though). If you find problems with the new prerelease just let me know. There is now a full example app in `./example` which covers a lot of use cases. If things aren't working a test-case may be added there to reproduce the problem

**Comment by mrousavy** [comment]
@ everyone having the same issue: I've added the v4 packages as `devDependencies` for now, which works perfectly fine.

```json
"react-navigation": "^4.3.7",
"react-navigation-stack": "^2.3.11"
```

(`dependencies` still contains the new `react-navigation` and `react-navigation-stack` packages)

**Comment by dotfelixb** [comment]
This is what I installed and it's working okay

```
 "react-native-shared-element": "^0.7.0",
 "react-navigation-shared-element": "^5.0.0-alpha1"
```

**Comment by luco** [comment]
Getting this as well.

**Comment by nandorojo** [comment]
> ```json
> "react-navigation": "^4.3.7",
> "react-navigation-stack": "^2.3.11"
> ```

Adding these to my dev dependencies and running `yarn` solved this for me too.

**Comment by danielmark0116** [comment]
@dotfelixb versions configuration was also working fine in my case. However, when navigating back, the shared element's animation was not being triggered on Android. Eventually, I just went back to the "react-navigation-shared-element": "3.0.0" + 
```
"react-navigation": "^4.3.7",
"react-navigation-stack": "^2.3.11"
```
installed as devDeps

Now it works fine on both platforms :)

**Comment by rahulkasana** [comment]
I'm having this same issue sometimes. But when i try to add react-navigation && react-navigation-stack as dev dependencies then i get this error. Anyone has a better solution or a fork of this repo which works with react-navigation-5 ?
`Invariant Violation: Please specify at least one route when configuring a navigator.`

**Comment by IjzerenHein** [comment]
The earlier 3.0.0 prerelease version was a bit clunky and didn't decouple react-navigation 4 & 5 correctly. [A new major version](https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2) has just been released which with solves these issues. Please view the main [README](https://github.com/IjzerenHein/react-navigation-shared-element) on how to use it.
