### ISSUE TITLE
Won't work with nested createBottomTabNavigator.

### ISSUE THREAD

**Issue by fachryansyah** [IjzerenHein/react-navigation-shared-element#8]
Using createStackNavigator is working perfectly, but shared element won't work when combine it to createBottomTabNavigator.

please next update added for nested creareBottomTabNavigator

**Comment by IjzerenHein** [comment]
Hi, thanks for reporting this.
I've been too busy with other projects lately but will hopefully take a closer within the next two weeks.
cheers

**Comment by JeanMonteiro** [comment]
any news? i'm needing it too.

**Comment by IjzerenHein** [comment]
Hi. I've begun work on v2 of this lib, which will work with react-navigation-stack@2. I have nested navigators  working in that version. If you are interested in testing, please take a look here:
https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/README_v2.md

**Comment by IjzerenHein** [comment]
V2 has been released, and should fix this.
Let me know if there are still any issues.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.0.1

**Comment by chrisid** [comment]
I've been testing this on a new App with bottom tabs and it's working like a charm!

**Comment by IjzerenHein** [comment]
Closing this as it seems to work now!

**Comment by frankcalise** [comment]
But we couldn't share an element between a navigator measured in a tab bar over to a modal stack, right?

App Stack
  Tabs
  Modal

TabStack
  Stack 1
  Stack 2

Stack 1
 Screen 1
 ... Etc
