### ISSUE TITLE
SharedElement typescript definitions is missing View props

### ISSUE THREAD

**Issue by iamsuneeth** [IjzerenHein/react-navigation-shared-element#9]
As per documentation SharedElement supports all VIew element props. But if any of the view props are used, for example, style prop, typescript throws Property 'style' does not exist.

Property | Type | Description
-- | -- | --
children | element | A single child component, which must map to a real view in the native view hierarchy
id | string | Unique id of the shared element
View props... |   | Other props supported by View

**Comment by iamsuneeth** [comment]
Pull request for this issue 
https://github.com/IjzerenHein/react-navigation-shared-element/pull/10

**Comment by IjzerenHein** [comment]
Awesome, thanks for the PR, will take a closer look when I have more time!

**Comment by IjzerenHein** [comment]
Thanks bro! I've released the update:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v1.0.0

cheers, Hein
