### ISSUE TITLE
Separate support for 4.x and 5.x APIs of react-navigation.

### ISSUE THREAD

**Issue by phamhoaivu911** [IjzerenHein/react-navigation-shared-element#95]
# Description
To use the prerelease v3,
> which unifies the 4.x and 5.x APIs of react-navigation in a single codebase

with react-navigation 5.x, I have to also install react-navigation 4.x. If I don't, it will raise this error.

<img width="340" alt="Screen Shot 2020-08-14 at 14 59 08" src="https://user-images.githubusercontent.com/4929170/90227415-b8eb7a00-de3e-11ea-8b1f-52518f581430.png">|
:-:|

Since I'm using 5.x version, I don't want to install 4.x version into my app. 

I guess this is already in the plan that supports for 4.x and 5.x APIs of react-navigation will be separated in the final release.

Again, thanks for the great library 🎉

**Comment by Jonovono** [comment]
Yep, same issue as me @phamhoaivu911 did you find a workaround for now?

**Comment by EliasFl** [comment]
This is happening to me, any workaround on this?

**Comment by IjzerenHein** [comment]
Done, see the official 3.x release:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2
